// JourneyLibrary.swift
// 6 new premium journey series (30 days each = 180 devotionals)

import Foundation

// swiftlint:disable file_length type_body_length

struct JourneyLibrary {

    private struct DayData {
        let week: Int
        let theme: String
        let scripture: String
        let devotional: String
        let anchor: String
        let arrow: String
    }

    private static func build(_ data: [DayData]) -> [JourneyDay] {
        data.enumerated().map { index, item in
            JourneyDay(
                id: index + 1,
                week: item.week,
                theme: item.theme,
                scripture: item.scripture,
                devotional: item.devotional,
                anchorPrompt: item.anchor,
                arrowPrompt: item.arrow,
                isUnlocked: index == 0,
                completedDate: nil
            )
        }
    }

    static func theFathersHeartDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "The God Who Runs", scripture: "Luke 15:20",
                devotional: "The father in the parable doesn't wait at the door with crossed arms. He runs. In the ancient world, a dignified man never ran. But this father hikes up his robe and sprints toward his wrecked son. That's the God you serve. Not a distant judge. A Father who runs toward you in your mess.",
                anchor: "What is your honest image of God as Father? Is it accurate?",
                arrow: "Tell someone today what you are learning about God's fatherly love."),
            DayData(week: 1, theme: "Before You Ask", scripture: "Matthew 6:8",
                devotional: "Your Father knows what you need before you ask Him. That doesn't make prayer pointless. It makes it relational. You're not informing God. You're opening your hands to a Father who was already reaching.",
                anchor: "What need are you trying to meet on your own that you haven't brought to the Father?",
                arrow: "Pray about one specific need today out loud and let it go."),
            DayData(week: 1, theme: "Adopted, Not Orphaned", scripture: "Romans 8:15",
                devotional: "You did not receive a spirit of slavery to fall back into fear, but a spirit of adoption. The word Abba is intimate. Orphan thinking says: I have to earn it. Son thinking says: I am already loved, already chosen, already home.",
                anchor: "Where does orphan thinking still drive you?",
                arrow: "Identify one area where you can rest in sonship instead of striving."),
            DayData(week: 1, theme: "The Discipline of a Father", scripture: "Hebrews 12:6",
                devotional: "The Lord disciplines those He loves. God's discipline is not anger. It is formation. A father who never corrects his son does not love him. The trial you're in might not be punishment. It might be training.",
                anchor: "What current difficulty might be God's fatherly discipline?",
                arrow: "Submit to one area of correction today instead of resisting it."),
            DayData(week: 1, theme: "He Calls You Son", scripture: "1 John 3:1",
                devotional: "See what kind of love the Father has given to us, that we should be called children of God. Not servants. Not followers. Children. Sons. That's your identity. The world measures men by output. God measures you by one thing: you are His.",
                anchor: "Do you believe you are God's son? Where does doubt creep in?",
                arrow: "Live today as a son of God. Not performing. Not proving. Just being His."),
            DayData(week: 1, theme: "The Waiting Father", scripture: "Luke 15:28-31",
                devotional: "The older brother served like a slave, not a son. He obeyed for reward, not relationship. Many Christian men are older brothers. Faithful on the outside, resentful on the inside. The Father is not asking for your performance. He wants your presence.",
                anchor: "Are you more like the younger brother or the older brother?",
                arrow: "Do one thing today purely out of love for the Father. Not duty, not guilt."),
            DayData(week: 1, theme: "Abba in the Garden", scripture: "Mark 14:36",
                devotional: "In His darkest moment, facing the cross, Jesus cried out: Abba, Father. Not Almighty God. Not Lord of Hosts. Abba. Dad. If Jesus needed to cry out to the Father in suffering, how much more do you?",
                anchor: "When was the last time you cried out to God as Father desperately?",
                arrow: "If you are carrying something heavy, stop and say Abba Father out loud."),
            DayData(week: 2, theme: "A Father Provides", scripture: "Matthew 7:11",
                devotional: "If you, being imperfect, know how to give good gifts to your children, how much more will your Father in heaven give good things? God's provision is not reluctant. He gives like a Father who delights in His children.",
                anchor: "Where are you anxious about provision?",
                arrow: "Provide generously for someone today reflecting the Father's heart."),
            DayData(week: 2, theme: "A Father Protects", scripture: "Psalm 91:4",
                devotional: "He will cover you with His feathers, and under His wings you will find refuge. The image is tender and fierce at the same time. God's protection is not passive. That's the kind of father you are called to be.",
                anchor: "Where do you need the Father's protection today?",
                arrow: "Protect someone in your care today with both strength and tenderness."),
            DayData(week: 2, theme: "A Father Corrects", scripture: "Proverbs 3:11-12",
                devotional: "Do not despise the Lord's discipline. God's correction is precise. It targets the behavior, not your identity. You are loved AND you need to change. Both things are true.",
                anchor: "How do you typically respond to correction? Defensiveness or shame?",
                arrow: "Receive one piece of correction today without defending yourself."),
            DayData(week: 2, theme: "A Father Delights", scripture: "Zephaniah 3:17",
                devotional: "He will rejoice over you with gladness. He will quiet you by His love. He will exult over you with loud singing. God sings over you. Not because you performed well. He sings because you are His.",
                anchor: "Can you receive the idea that God delights in you?",
                arrow: "Delight in someone today the way the Father delights in you."),
            DayData(week: 2, theme: "A Father Releases", scripture: "Luke 15:12-13",
                devotional: "The father let the younger son go. That's the hardest thing a father does: release. God does not force obedience. He invites, He warns, He waits. But He will not override your freedom.",
                anchor: "Is there someone you need to release to God's care?",
                arrow: "Let go of one thing you have been gripping today."),
            DayData(week: 2, theme: "A Father Restores", scripture: "Hosea 11:1-4",
                devotional: "When Israel was a child, I loved him. I taught him to walk, taking him by the arms. Hosea reveals a God who is heartbroken over His wandering children. Not angry first, but grieving. He taught them to walk. He bent down.",
                anchor: "Where has the Father been gently restoring you?",
                arrow: "Be an agent of restoration today."),
            DayData(week: 2, theme: "Becoming the Father", scripture: "Ephesians 3:14-15",
                devotional: "From whom every family derives its name. Every concept of fatherhood flows from God. You become a good father by receiving from the original Father and passing it on. The fatherhood gap is filled by encounter, not willpower.",
                anchor: "How has your understanding of God as Father shaped how you lead at home?",
                arrow: "Do one fatherly thing today: provide, protect, correct with love, or simply be present."),
            DayData(week: 3, theme: "The Wound Most Men Carry", scripture: "Psalm 27:10",
                devotional: "Many men carry a father wound: absence, abuse, indifference, performance-based love. This wound shapes everything. David's father did not even present him when Samuel came looking. But God saw him.",
                anchor: "What is your father wound? Name it honestly.",
                arrow: "Bring this wound to God in prayer today. Just name it before Him."),
            DayData(week: 3, theme: "Forgiveness Is Freedom", scripture: "Colossians 3:13",
                devotional: "Forgiveness does not mean what happened was okay. It means you are no longer willing to carry the weight. Unforgiveness toward a father is one of the heaviest chains a man can wear.",
                anchor: "Is there unforgiveness toward your father that you are still carrying?",
                arrow: "Take one step toward forgiveness today."),
            DayData(week: 3, theme: "Breaking the Cycle", scripture: "Ezekiel 18:20",
                devotional: "The son shall not suffer for the iniquity of the father. You are not condemned to repeat your father's patterns. In Christ, generational chains break. But they do not break passively.",
                anchor: "What pattern from your family are you at risk of repeating?",
                arrow: "Take one concrete step to break a generational pattern."),
            DayData(week: 3, theme: "God Replaces What Was Missing", scripture: "Psalm 68:5-6",
                devotional: "A father to the fatherless. God sets the lonely in families. If you did not get the father you needed, God says I will be that for you. Not as a concept. As a reality.",
                anchor: "Where are the gaps in your fathering experience? Invite God to fill them.",
                arrow: "Be a spiritual father to someone today who does not have one."),
            DayData(week: 3, theme: "The Father You Needed", scripture: "Isaiah 49:15-16",
                devotional: "I have engraved you on the palms of my hands. Your name is carved into God's hands. Permanent. Whatever your earthly father forgot, God has not forgotten you.",
                anchor: "What did your earthly father forget that still hurts?",
                arrow: "Remember someone today who might feel forgotten."),
            DayData(week: 3, theme: "No Longer Striving", scripture: "Romans 8:16-17",
                devotional: "The Spirit testifies that we are God's children. If children, then heirs. You do not earn an inheritance. You receive it by birth. Stop striving for what is already yours.",
                anchor: "Where are you still earning what God has already given?",
                arrow: "Rest in one area today. Receive instead of achieve."),
            DayData(week: 3, theme: "Seated at the Table", scripture: "Luke 15:22-24",
                devotional: "The prodigal got a robe, a ring, sandals, and a feast. Not punishment. Not probation. Full restoration. Whatever you have done, the table is set.",
                anchor: "Have you fully accepted that God celebrates your return?",
                arrow: "Celebrate someone's return today. Welcome them back."),
            DayData(week: 4, theme: "Passing the Baton", scripture: "Deuteronomy 6:6-7",
                devotional: "Faith does not transfer by osmosis. It transfers by intention. Your children need to see your faith in action. They are not listening to your sermons. They are watching your life.",
                anchor: "What is your faith teaching the next generation right now?",
                arrow: "Have one intentional spiritual conversation with someone younger today."),
            DayData(week: 4, theme: "Present, Not Perfect", scripture: "Proverbs 22:6",
                devotional: "Training requires presence. You cannot train from a distance. Your kids do not need a perfect father. They need a present one who loves God imperfectly but persistently.",
                anchor: "Are you present in the lives of those you are called to father?",
                arrow: "Be physically and emotionally present for someone who needs you today."),
            DayData(week: 4, theme: "Leaving a Legacy", scripture: "Psalm 78:4",
                devotional: "We will tell the next generation the praiseworthy deeds of the Lord. Your legacy is not your bank account. It is the faith you pass on. Legacy is built in the mundane.",
                anchor: "What legacy are you building?",
                arrow: "Do one legacy-building act today."),
            DayData(week: 4, theme: "Blessing Your Children", scripture: "Numbers 6:24-26",
                devotional: "The Lord bless you and keep you. Blessing is a father speaking God's truth over the people in his care. Words have weight. A father's blessing can shape a lifetime.",
                anchor: "When did you last speak a blessing over someone in your care?",
                arrow: "Speak a blessing over someone today out loud."),
            DayData(week: 4, theme: "The Father Who Stays", scripture: "Joshua 1:5",
                devotional: "I will never leave you nor forsake you. God does not leave. He stays in your failure. He stays in your wandering. He stays when you push Him away.",
                anchor: "Do you believe God stays even in your worst moments?",
                arrow: "Stay for someone today. Be present when it would be easier to leave."),
            DayData(week: 4, theme: "From Fatherless to Father", scripture: "2 Corinthians 1:3-4",
                devotional: "The God of all comfort, who comforts us so that we can comfort those in any trouble. Your wound becomes your ministry. The fathering you did not receive from man, you receive from God and give away.",
                anchor: "How is God turning your father wound into a ministry?",
                arrow: "Father someone today who does not have one."),
            DayData(week: 4, theme: "Coming Home", scripture: "Luke 15:24",
                devotional: "This son of mine was dead and is alive again; he was lost and is found. Whatever road you have been on, the Father's door is open. The feast is prepared. The robe is ready. Come home.",
                anchor: "Is there any part of your heart that has not fully come home to the Father?",
                arrow: "Come home today. Fully. No reservations."),
            DayData(week: 4, theme: "Abba's Blessing", scripture: "Ephesians 1:3",
                devotional: "Blessed be the God and Father who has blessed us with every spiritual blessing in Christ. Every blessing. Not some. Every. You are a blessed son of a good Father.",
                anchor: "Name three specific blessings the Father has given you.",
                arrow: "Write a prayer of gratitude to the Father."),
            DayData(week: 4, theme: "Son of the Father", scripture: "1 John 3:2",
                devotional: "Beloved, we are God's children now, and what we will be has not yet appeared. You are God's child NOW. The Father is still working. The story is not over.",
                anchor: "How has your understanding of the Father's heart changed?",
                arrow: "Tell one person today what you have learned about God as Father."),
        ])
    }

    static func warriorMindsetDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "You Are at War", scripture: "1 Peter 5:8",
                devotional: "Your adversary the devil prowls around like a roaring lion. Most men live like they are on vacation. But you have an adversary. He is strategic. And he is looking for the man who is distracted or isolated.",
                anchor: "Are you living like a man at war or on vacation?",
                arrow: "Identify one spiritual vulnerability and build a defense today."),
            DayData(week: 1, theme: "Flesh vs. Spirit", scripture: "Galatians 5:17",
                devotional: "The flesh desires what is contrary to the Spirit. You fight an internal war. Your flesh wants comfort, control, gratification. The Spirit wants surrender, obedience, freedom. Which side will you feed today?",
                anchor: "Where is the flesh winning in your life right now?",
                arrow: "Starve one fleshly desire and feed the Spirit today."),
            DayData(week: 1, theme: "The Battlefield of the Mind", scripture: "2 Corinthians 10:5",
                devotional: "We take every thought captive. The war is won or lost in your mind. Every sin starts as a thought. Taking thoughts captive is active, not passive.",
                anchor: "What recurring thought pattern is the enemy using against you?",
                arrow: "Catch one lie today and replace it with Scripture."),
            DayData(week: 1, theme: "The Schemes", scripture: "Ephesians 6:11",
                devotional: "Put on the full armor of God to stand against the devil's schemes. The enemy has a method. He studies your patterns and vulnerabilities. Once you recognize the play, you can defend against it.",
                anchor: "What scheme does the enemy keep running against you?",
                arrow: "Prepare a defense for your most vulnerable moment today."),
            DayData(week: 1, theme: "Resist and He Flees", scripture: "James 4:7",
                devotional: "Submit to God. Resist the devil and he will flee. The order matters. Submit first, then resist. You cannot fight the enemy while in rebellion against God.",
                anchor: "Are you submitted to God in the area where you are under attack?",
                arrow: "Submit one area to God today, then actively resist."),
            DayData(week: 1, theme: "Prayer as Warfare", scripture: "Ephesians 6:18",
                devotional: "Pray in the Spirit on all occasions. Prayer is not the warm-up to the fight. Prayer IS the fight. The enemy does not fear your strength. He fears your prayers.",
                anchor: "Is your prayer life a weapon or a routine?",
                arrow: "Pray offensively today against spiritual strongholds."),
            DayData(week: 1, theme: "The Victory Is Won", scripture: "Colossians 2:15",
                devotional: "Having disarmed the powers, He made a public spectacle of them, triumphing by the cross. The war is already won. You fight from victory, not toward it. The enemy is defeated with a loud voice.",
                anchor: "Do you fight like a man who has already won?",
                arrow: "Walk into your hardest battle with the confidence that Christ has already won it."),
            DayData(week: 2, theme: "The Word as Sword", scripture: "Hebrews 4:12",
                devotional: "The word of God is living and active, sharper than any sword. Jesus defeated the devil with three words: It is written. The Word is your primary offensive weapon.",
                anchor: "What verse do you have memorized for battle?",
                arrow: "Memorize one verse that counters your most common temptation."),
            DayData(week: 2, theme: "Worship as Warfare", scripture: "2 Chronicles 20:22",
                devotional: "As they began to sing and praise, the Lord set ambushes. Jehoshaphat sent worshippers first, not soldiers. Worship shifts the atmosphere from the size of the enemy to the size of your God.",
                anchor: "When was the last time you worshipped in the middle of a battle?",
                arrow: "Put on worship music during your hardest moment today."),
            DayData(week: 2, theme: "Fasting as a Weapon", scripture: "Matthew 17:21",
                devotional: "This kind does not go out except by prayer and fasting. Some battles require heavier weapons. Fasting is a declaration of dependence on God over your flesh.",
                anchor: "What battle might require fasting?",
                arrow: "Consider a fast for a specific battle. Set a date."),
            DayData(week: 2, theme: "Community as Defense", scripture: "Ecclesiastes 4:12",
                devotional: "A cord of three strands is not quickly broken. The enemy's first move is always isolation. Lone warriors die. Men in formation survive.",
                anchor: "Are you fighting alone or in formation?",
                arrow: "Tell one brother your biggest struggle today. Break isolation."),
            DayData(week: 2, theme: "The Shield of Faith", scripture: "Ephesians 6:16",
                devotional: "Take up the shield of faith to extinguish all the flaming arrows. The arrows are real: doubt, lust, fear, discouragement. Faith is a decision to trust God's character when the arrows say He is absent.",
                anchor: "What fiery arrow has been hitting you? What truth extinguishes it?",
                arrow: "Raise your shield today. Speak the truth out loud when the arrow comes."),
            DayData(week: 2, theme: "The Authority of Christ", scripture: "Luke 10:19",
                devotional: "I have given you authority to trample on snakes and scorpions. You have authority. Not your own but Christ's, delegated to you. Start walking in the authority you have been given.",
                anchor: "Do you walk in spiritual authority or timidity?",
                arrow: "Exercise spiritual authority over one area today."),
            DayData(week: 2, theme: "Standing, Not Advancing", scripture: "Ephesians 6:13",
                devotional: "Having done everything, stand. Sometimes the posture is not charging forward but holding the line. The ground you have taken is worth defending.",
                anchor: "Where do you need to hold your ground?",
                arrow: "Stand firm in one area today. No ground given."),
            DayData(week: 3, theme: "The Stronghold Within", scripture: "2 Corinthians 10:4",
                devotional: "The weapons we fight with have divine power to demolish strongholds. A stronghold is a fortified thought pattern, a lie believed so long it feels like truth. They require divine power to tear down.",
                anchor: "What stronghold has been fortified in your mind for years?",
                arrow: "Speak the opposite truth over that stronghold today."),
            DayData(week: 3, theme: "Identity Under Attack", scripture: "Genesis 3:1",
                devotional: "Did God really say? The enemy's primary strategy: make you doubt what God said about you. Your identity in Christ is the most attacked part of your life.",
                anchor: "What does God say about you that the enemy keeps making you doubt?",
                arrow: "Write down three identity truths and read them out loud."),
            DayData(week: 3, theme: "Anger as a Weapon", scripture: "Ephesians 4:26-27",
                devotional: "Be angry and do not sin. Do not let the sun go down on your anger. Give no opportunity to the devil. Unresolved anger is an open door for the enemy.",
                anchor: "Is there unresolved anger giving the enemy a foothold?",
                arrow: "Resolve one anger issue today. Confess, address, or release it."),
            DayData(week: 3, theme: "The Discipline of Vigilance", scripture: "1 Corinthians 16:13",
                devotional: "Be on your guard. Stand firm. Be courageous. Be strong. Four commands. Every morning you suit up. Every evening you debrief. The warrior life is disciplined.",
                anchor: "Which command is weakest: guard, firm, courageous, strong?",
                arrow: "Strengthen your weakest area with one specific action today."),
            DayData(week: 3, theme: "Suffering as Training", scripture: "James 1:2-4",
                devotional: "The testing of your faith produces perseverance. Warriors train under pressure. The trial is training, not punishment. The muscle only grows under resistance.",
                anchor: "What trial might be warrior training rather than punishment?",
                arrow: "Face one hard thing today with the mindset of a warrior in training."),
            DayData(week: 3, theme: "Guard Your Eyes", scripture: "Job 31:1",
                devotional: "I made a covenant with my eyes. Job made a covenant before the temptation arrived. The warrior who waits until battle to build defenses has already lost.",
                anchor: "What covenant do you need to make before temptation arrives?",
                arrow: "Set one boundary on your eyes or screen today."),
            DayData(week: 3, theme: "The Warrior's Rest", scripture: "Psalm 23:2",
                devotional: "He makes me lie down in green pastures. Even warriors rest. A warrior who never rests becomes reckless, then useless. Know when to fight and when to be still.",
                anchor: "Are you resting enough, or burning out?",
                arrow: "Take deliberate rest today. Not scrolling. Actual rest."),
            DayData(week: 4, theme: "Fight for Others", scripture: "Nehemiah 4:14",
                devotional: "Fight for your families, your sons and daughters, your wives and your homes. The warrior does not fight for himself. He fights for those behind him.",
                anchor: "Who are you fighting for beyond yourself?",
                arrow: "Fight for someone today. Intercede, protect, stand up."),
            DayData(week: 4, theme: "Pass the Sword", scripture: "2 Timothy 2:2",
                devotional: "Entrust to reliable men who will teach others. The ultimate warrior mission is training other warriors. Teach someone to fight.",
                anchor: "Who are you training to be a spiritual warrior?",
                arrow: "Share one warfare principle with a younger man today."),
            DayData(week: 4, theme: "The Warrior's Reward", scripture: "2 Timothy 4:7-8",
                devotional: "I have fought the good fight. Now there is a crown of righteousness. The crown is for the man who kept fighting. Not perfection but persistence.",
                anchor: "Can you say you have fought the good fight about this season?",
                arrow: "Fight one more round today. The crown is ahead."),
            DayData(week: 4, theme: "Victory Formation", scripture: "Romans 8:37",
                devotional: "In all these things we are more than conquerors through Him who loved us. Not barely surviving. More than conquerors. Through Him. Walk in victory formation.",
                anchor: "Are you walking in victory or defeat?",
                arrow: "Walk into your biggest challenge as more than a conqueror."),
            DayData(week: 4, theme: "The Battle Belongs to the Lord", scripture: "2 Chronicles 20:15",
                devotional: "The battle is not yours, but God's. Release the outcome. Fight faithfully and trust the Commander with the results.",
                anchor: "What battle do you need to hand back to God?",
                arrow: "Release one battle to the Lord today."),
            DayData(week: 4, theme: "Spiritual Endurance", scripture: "Hebrews 12:1",
                devotional: "Let us run with perseverance the race marked out for us. The race is not a sprint. It is a marathon. The warrior who trains for endurance outlasts the one who trains for speed. Perseverance is the unsexy virtue that wins wars.",
                anchor: "Are you training for a sprint or a marathon?",
                arrow: "Build endurance today. Do the hard thing slowly and consistently."),
            DayData(week: 4, theme: "The Warrior Community", scripture: "2 Samuel 23:8-12",
                devotional: "David's mighty men stood their ground and struck down the enemy until their hands were frozen to their swords. These men fought so hard their hands fused to the weapon. They did not fight alone. They fought together. And their names are remembered forever.",
                anchor: "Do you fight with the intensity of David's mighty men? What holds you back?",
                arrow: "Fight alongside a brother today. Together you are stronger."),
            DayData(week: 4, theme: "Sheathe the Sword", scripture: "Matthew 26:52",
                devotional: "Put your sword back in its place. The warrior knows when to fight and when to stand down. Not every battle is yours. Not every offense requires a response. Wisdom knows the difference between a battle worth fighting and a distraction disguised as a war.",
                anchor: "What battle are you fighting that is not actually yours?",
                arrow: "Sheathe your sword in one area today. Let God fight that one."),
            DayData(week: 4, theme: "Warrior Benediction", scripture: "Ephesians 6:10",
                devotional: "Finally, be strong in the Lord and in His mighty power. You are a warrior of the Most High God. Not by your strength but by His. Stand firm. Fight well.",
                anchor: "How has the warrior mindset shifted your daily life?",
                arrow: "Commit to living as a spiritual warrior every day."),
        ])
    }

    static func theNarrowRoadDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "The Narrow Gate", scripture: "Matthew 7:13-14",
                devotional: "The narrow road is not popular or comfortable. But it is the only one that leads to life. Every day you choose: the wide road of cultural default or the narrow road of intentional discipleship.",
                anchor: "Where are you drifting onto the wide road?",
                arrow: "Make one narrow-road choice today that goes against the current."),
            DayData(week: 1, theme: "Poor in Spirit", scripture: "Matthew 5:3",
                devotional: "The kingdom starts with emptiness. Spiritual poverty is the honest admission that you have nothing to offer God. This is the opposite of everything the world teaches men.",
                anchor: "Are you spiritually self-sufficient or spiritually poor?",
                arrow: "Approach one situation from dependence on God today."),
            DayData(week: 1, theme: "Mourning and Comfort", scripture: "Matthew 5:4",
                devotional: "Blessed are those who mourn. Men are taught not to mourn. But Jesus says mourning is the pathway to comfort. The man who can grieve is the man who can be comforted.",
                anchor: "What are you refusing to mourn?",
                arrow: "Allow yourself to grieve one thing today. Bring it to God."),
            DayData(week: 1, theme: "The Meek Inherit", scripture: "Matthew 5:5",
                devotional: "Meekness is not weakness. It is power under control. A meek man has the strength to retaliate but chooses restraint. The world rewards aggression. Jesus rewards meekness.",
                anchor: "Where do you need to exercise power under control?",
                arrow: "Choose restraint in one situation where you could assert power."),
            DayData(week: 1, theme: "Hunger for Righteousness", scripture: "Matthew 5:6",
                devotional: "Are you hungry? Not for success or comfort but for righteousness? The filling only comes to the hungry. Holy dissatisfaction is a gift. It drives you deeper.",
                anchor: "How hungry are you for God right now?",
                arrow: "Feed your spiritual hunger today. Do not settle for snacking."),
            DayData(week: 1, theme: "Mercy Receives Mercy", scripture: "Matthew 5:7",
                devotional: "Mercy is giving someone what they do not deserve, the way God gave you what you do not deserve. The merciful man is generous with grace because he knows how much he has received.",
                anchor: "Who needs your mercy today?",
                arrow: "Show mercy to one person who does not deserve it."),
            DayData(week: 1, theme: "Pure in Heart", scripture: "Matthew 5:8",
                devotional: "Purity is not just about what you avoid. It is about what you pursue. A pure heart is undivided. It wants one thing: God. The impure heart is split between God and the world.",
                anchor: "Is your heart divided? What competes with God?",
                arrow: "Purify one area of your heart today."),
            DayData(week: 2, theme: "Salt of the Earth", scripture: "Matthew 5:13",
                devotional: "Salt preserves and flavors. You are meant to preserve godliness and add meaning where it is absent. If your faith makes no visible difference, you have lost your saltiness.",
                anchor: "Where are you being salt in your environment?",
                arrow: "Be salt in one specific context today."),
            DayData(week: 2, theme: "Light of the World", scripture: "Matthew 5:14-16",
                devotional: "Your light is not your theology or social media. It is your life. How you treat the waiter. How you respond when tired. The world sees your light in the mundane.",
                anchor: "What does your light reveal to others?",
                arrow: "Let your light shine in one mundane moment today."),
            DayData(week: 2, theme: "Heart of the Law", scripture: "Matthew 5:21-22",
                devotional: "Jesus did not lower the bar. He raised it. It is not enough to avoid the act. The heart matters. You may not have committed murder, but have you assassinated someone's character?",
                anchor: "Where is your external behavior clean but your heart compromised?",
                arrow: "Address one heart issue that behavior has been masking."),
            DayData(week: 2, theme: "Turn the Other Cheek", scripture: "Matthew 5:39",
                devotional: "This is not passivity. It is radical strength. Refusing to retaliate on their terms. The man who turns the other cheek is so secure in his identity that an insult cannot move him.",
                anchor: "Where are you tempted to retaliate?",
                arrow: "Refuse to retaliate in one situation today."),
            DayData(week: 2, theme: "Love Your Enemies", scripture: "Matthew 5:44",
                devotional: "This is the most countercultural command Jesus ever gave. Loving someone who wronged you requires supernatural love. It is the narrowest part of the narrow road.",
                anchor: "Who is hardest for you to love right now?",
                arrow: "Pray for that person by name today."),
            DayData(week: 2, theme: "Secret Righteousness", scripture: "Matthew 6:1-4",
                devotional: "If your faith only shows up when people are watching, it is performance. Jesus calls for secret righteousness, where only the Father sees. The reward of secret devotion surpasses public praise.",
                anchor: "What spiritual practice do you only do when others watch?",
                arrow: "Do one righteous act today that no one will ever know about."),
            DayData(week: 2, theme: "Store Up Treasures", scripture: "Matthew 6:19-21",
                devotional: "Your calendar and bank account reveal what you truly treasure. The narrow road redirects your treasure from the temporary to the eternal.",
                anchor: "If someone audited your time and money, what would they say you treasure?",
                arrow: "Invest in one eternal thing today."),
            DayData(week: 3, theme: "Do Not Worry", scripture: "Matthew 6:25-27",
                devotional: "Worry is functional atheism. It says God is not handling this, so I better. Jesus does not say try not to worry. He says don't. The Father is bigger than the problem.",
                anchor: "What are you worrying about that worry cannot change?",
                arrow: "Replace one worry with one prayer today."),
            DayData(week: 3, theme: "Seek First", scripture: "Matthew 6:33",
                devotional: "Seek first His kingdom and His righteousness, and all these things will be given. The order is everything. Most men seek the things first and add God when convenient.",
                anchor: "What are you seeking first today honestly?",
                arrow: "Put God's kingdom first in one decision today."),
            DayData(week: 3, theme: "Judge Not", scripture: "Matthew 7:1-5",
                devotional: "Why do you look at the speck in your brother's eye? Deal with yours first. The man who leads with humility about his own failures earns the right to speak into others' lives.",
                anchor: "Where are you judging others for something you struggle with?",
                arrow: "Remove one plank from your own eye today."),
            DayData(week: 3, theme: "Ask, Seek, Knock", scripture: "Matthew 7:7-8",
                devotional: "Three escalating levels of pursuit. Asking is verbal. Seeking is active. Knocking is persistent. God rewards all three but He is looking for men who do not give up.",
                anchor: "Where have you given up asking God?",
                arrow: "Knock on one door again that you thought was closed."),
            DayData(week: 3, theme: "The Golden Rule", scripture: "Matthew 7:12",
                devotional: "In everything, do to others what you would have them do to you. Before you speak, send that text, make that decision, ask: how would I want to be treated?",
                anchor: "Where are you treating others in a way you would not want?",
                arrow: "Apply the golden rule to one difficult relationship today."),
            DayData(week: 3, theme: "Fruit Reveals Root", scripture: "Matthew 7:16-20",
                devotional: "Your life produces fruit whether you intend it to or not. Good fruit comes from abiding in Christ. Look at the fruit of your life and you will see your root.",
                anchor: "What fruit is your life producing? What root grows it?",
                arrow: "Cultivate one good root today and trust the fruit to follow."),
            DayData(week: 3, theme: "Lord, Lord", scripture: "Matthew 7:21-23",
                devotional: "Not everyone who says Lord, Lord will enter the kingdom. These are the most terrifying words Jesus spoke. It is possible to call Him Lord and not know Him.",
                anchor: "Is your faith built on knowing God or religious activity?",
                arrow: "Do one thing today that reflects knowing God, not just knowing about Him."),
            DayData(week: 4, theme: "The Wise Builder", scripture: "Matthew 7:24-25",
                devotional: "Everyone who hears these words and puts them into practice is like a wise man who built on the rock. Hearing is not enough. The wise builder practices what he hears. The storm hits both houses. The difference is the foundation.",
                anchor: "Is your life built on the rock of obedience or the sand of good intentions?",
                arrow: "Put one teaching into practice today."),
            DayData(week: 4, theme: "The Foolish Builder", scripture: "Matthew 7:26-27",
                devotional: "The fool heard the same sermon. He just did not act on it. Information without application is sand. When the storm comes, sand collapses.",
                anchor: "What truth do you know that you are not living?",
                arrow: "Convert one piece of knowledge into obedience today."),
            DayData(week: 4, theme: "Narrow Road Relationships", scripture: "Matthew 5:23-24",
                devotional: "If you remember that your brother has something against you, leave your gift. Go and be reconciled. Your relationships take priority over religious practices.",
                anchor: "Is there a relationship you need to reconcile?",
                arrow: "Take one step toward reconciliation today."),
            DayData(week: 4, theme: "Daily Bread Trust", scripture: "Matthew 6:11",
                devotional: "Give us today our daily bread. Not weekly. Not yearly. Daily. God provides one day at a time because He wants you to depend on Him one day at a time.",
                anchor: "Are you trying to secure tomorrow's bread today?",
                arrow: "Live in today. Take one step of trust."),
            DayData(week: 4, theme: "Forgive to Be Forgiven", scripture: "Matthew 6:14-15",
                devotional: "If you forgive other people, your heavenly Father will also forgive you. Forgiveness is not optional. It is the economy of the kingdom.",
                anchor: "Who do you need to forgive today?",
                arrow: "Release one person from a debt today."),
            DayData(week: 4, theme: "The Committed Life", scripture: "Matthew 5:37",
                devotional: "All you need to say is simply Yes or No. The narrow road demands integrity. Your word is your bond.",
                anchor: "Is your word reliable? Do people trust your yes and your no?",
                arrow: "Keep every commitment you make today."),
            DayData(week: 4, theme: "The Narrow Road Ahead", scripture: "Matthew 7:14",
                devotional: "Small is the gate and narrow the road that leads to life. You have spent 30 days on this road. It is not easy. But it leads to life.",
                anchor: "What has the narrow road cost you? What has it given you?",
                arrow: "Recommit to the narrow road today. Not for 30 days. For life."),
            DayData(week: 4, theme: "Authority of Christ", scripture: "Matthew 7:28-29",
                devotional: "The crowds were amazed because He taught with authority. The Sermon on the Mount is not advice. It is the authoritative word of the King. You have heard His words. Now build on them.",
                anchor: "Which teaching challenged you most?",
                arrow: "Obey the one teaching that challenged you most."),
            DayData(week: 4, theme: "The Road Continues", scripture: "Matthew 28:20",
                devotional: "Surely I am with you always, to the very end of the age. The narrow road continues. And the One who gave the Sermon walks beside you on every step.",
                anchor: "What has this journey revealed about the road ahead?",
                arrow: "Take the first step of the next chapter today."),
        ])
    }

    static func rootedAndBuiltDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "The Supremacy of Christ", scripture: "Colossians 1:15-17",
                devotional: "He is before all things and in Him all things hold together. Everything holds together in Christ. When life feels like it is falling apart, reconnect to the One who holds it all.",
                anchor: "What area feels like it is falling apart?",
                arrow: "Reconnect one area to Christ's lordship today."),
            DayData(week: 1, theme: "Rescued from Darkness", scripture: "Colossians 1:13-14",
                devotional: "He has rescued us from the dominion of darkness. You have been rescued. Past tense. You do not belong to darkness anymore. Live like a rescued man, not one still in chains.",
                anchor: "Are you living like a rescued man?",
                arrow: "Walk in freedom today. Darkness has no claim on you."),
            DayData(week: 1, theme: "Rooted in Christ", scripture: "Colossians 2:6-7",
                devotional: "Rooted and built up in Him. Roots go deep before the tree grows tall. Being rooted means the unseen work matters more than the visible growth.",
                anchor: "How deep are your roots?",
                arrow: "Do one root-building activity today that nobody will see."),
            DayData(week: 1, theme: "Complete in Christ", scripture: "Colossians 2:10",
                devotional: "In Christ you have been brought to fullness. You are complete now. Not incomplete until you fix your problems. The world says you need more. Paul says you already have fullness.",
                anchor: "Where are you looking for completeness outside of Christ?",
                arrow: "Rest in your completeness in Christ today."),
            DayData(week: 1, theme: "Dead to the Old", scripture: "Colossians 3:3",
                devotional: "You died, and your life is now hidden with Christ in God. The old you died with Christ. Your new life is hidden, secure, protected, anchored in God.",
                anchor: "What part of the old you keeps trying to resurrect?",
                arrow: "Put one old pattern to death today."),
            DayData(week: 1, theme: "Set Your Mind Above", scripture: "Colossians 3:1-2",
                devotional: "Set your minds on things above, not on earthly things. Where your mind goes, your life follows. Setting your mind above is not escapism. It is reorientation.",
                anchor: "Where is your mind set today?",
                arrow: "Reorient one decision through an eternal lens."),
            DayData(week: 1, theme: "Christ Is All", scripture: "Colossians 3:11",
                devotional: "Christ is all, and is in all. Not Christ plus your effort. Christ is all. The moment you add something to Christ as your foundation, you have built on sand.",
                anchor: "What have you been adding to Christ as your foundation?",
                arrow: "Depend entirely on Christ for one situation today."),
            DayData(week: 2, theme: "Put On Compassion", scripture: "Colossians 3:12",
                devotional: "Clothe yourselves with compassion, kindness, humility, gentleness and patience. These are not personality traits. They are wardrobe choices. You put them on deliberately.",
                anchor: "Which garment are you missing: compassion, kindness, humility, gentleness, or patience?",
                arrow: "Deliberately wear one of these garments today."),
            DayData(week: 2, theme: "Bear With Each Other", scripture: "Colossians 3:13",
                devotional: "Bear with each other and forgive. Bearing with someone means enduring their imperfections the way Christ endures yours.",
                anchor: "Who is hardest to bear with? Can you extend grace?",
                arrow: "Bear with one difficult person today without complaint."),
            DayData(week: 2, theme: "Let Peace Rule", scripture: "Colossians 3:15",
                devotional: "Let the peace of Christ rule in your hearts. The word rule means to act as umpire. Let Christ's peace call the shots in your decisions.",
                anchor: "Where are you making decisions without peace?",
                arrow: "Let peace rule one decision today."),
            DayData(week: 2, theme: "The Word Richly", scripture: "Colossians 3:16",
                devotional: "Let the message of Christ dwell among you richly. Not sparsely. Richly. Overflowing. How rich is Christ's word in your daily life?",
                anchor: "Is the Word dwelling richly or thinly in you?",
                arrow: "Increase your intake of the Word today."),
            DayData(week: 2, theme: "Whatever You Do", scripture: "Colossians 3:17",
                devotional: "Whatever you do, in word or deed, do it all in the name of the Lord. There is no sacred-secular divide. The emails, the errands, the commute. All of it can be done in His name.",
                anchor: "What part of your routine have you compartmentalized from God?",
                arrow: "Do one secular task explicitly in Jesus' name today."),
            DayData(week: 2, theme: "Work for the Lord", scripture: "Colossians 3:23-24",
                devotional: "Work at it with all your heart, as working for the Lord. Your boss is not your real audience. God is. Shift your audience and watch your motivation change.",
                anchor: "Who are you really working for?",
                arrow: "Work with excellence today as worship, not performance."),
            DayData(week: 2, theme: "Devote to Prayer", scripture: "Colossians 4:2",
                devotional: "Devote yourselves to prayer, being watchful and thankful. Devotion to prayer is a lifestyle. Paul adds watchfulness and thankfulness. A man who prays with open eyes and a grateful heart is dangerous.",
                anchor: "Is your prayer life devoted or occasional?",
                arrow: "Add watchfulness and thankfulness to your prayers today."),
            DayData(week: 3, theme: "Walk Wisely", scripture: "Colossians 4:5",
                devotional: "Be wise toward outsiders. Make the most of every opportunity. Every interaction with someone outside the faith is an opportunity. Not to preach but to live.",
                anchor: "How do outsiders experience your faith?",
                arrow: "Make the most of one interaction with an outsider today."),
            DayData(week: 3, theme: "Gracious Speech", scripture: "Colossians 4:6",
                devotional: "Let your conversation be full of grace, seasoned with salt. Grace and salt. Kindness and truth. Your words should make people feel valued and challenged.",
                anchor: "Are your words more salty or more gracious?",
                arrow: "Season one conversation with both grace and truth today."),
            DayData(week: 3, theme: "Mystery of Christ", scripture: "Colossians 1:27",
                devotional: "Christ in you, the hope of glory. Christ does not just stand beside you. He lives in you. The hope of glory is a present reality inside you right now.",
                anchor: "Do you live like Christ is in you?",
                arrow: "Carry the hope of glory into one dark situation today."),
            DayData(week: 3, theme: "Continue in Faith", scripture: "Colossians 1:23",
                devotional: "Continue in your faith, established and firm. The word continue is the key. Starting is easy. Continuing is the battle.",
                anchor: "Where are you tempted to quit?",
                arrow: "Continue today. Just one more day."),
            DayData(week: 3, theme: "Encourage Hearts", scripture: "Colossians 2:2",
                devotional: "My goal is that they may be encouraged in heart and united in love. Your roots intertwine with others. When one tree is rooted deep, it stabilizes the trees around it.",
                anchor: "Whose heart needs encouragement from you?",
                arrow: "Send one message of genuine encouragement today."),
            DayData(week: 3, theme: "Deceptive Philosophy", scripture: "Colossians 2:8",
                devotional: "See to it that no one takes you captive through hollow philosophy. Not every idea that sounds good is from God. Be rooted enough to discern.",
                anchor: "What cultural philosophy has subtly captured your thinking?",
                arrow: "Test one popular idea against Scripture today."),
            DayData(week: 3, theme: "New Self", scripture: "Colossians 3:10",
                devotional: "You have put on the new self, which is being renewed in knowledge in the image of its Creator. The new self is not finished. It is being renewed daily.",
                anchor: "In what way are you more like Christ than a year ago?",
                arrow: "Pursue one piece of transforming knowledge about God today."),
            DayData(week: 4, theme: "Husbands and Wives", scripture: "Colossians 3:19",
                devotional: "Husbands, love your wives and do not be harsh with them. Harshness destroys trust. Love your wife with patience, sacrifice, and gentleness.",
                anchor: "Have you been harsh in tone, words, or expectations?",
                arrow: "Replace one harsh habit with tenderness today."),
            DayData(week: 4, theme: "Fathers and Children", scripture: "Colossians 3:21",
                devotional: "Fathers, do not embitter your children. Your children need your encouragement more than your correction. Build them up.",
                anchor: "Are your children encouraged or embittered?",
                arrow: "Speak one specific encouragement to a child today."),
            DayData(week: 4, theme: "Faithful Servants", scripture: "Colossians 3:22-24",
                devotional: "Work with integrity whether or not anyone is watching. Character is who you are when no one is looking.",
                anchor: "Do you work differently when no one watches?",
                arrow: "Work with the same excellence in private as in public today."),
            DayData(week: 4, theme: "Pray for Open Doors", scripture: "Colossians 4:3",
                devotional: "Pray that God may open a door. Even Paul asked for prayer for open doors. The rooted man prays, prepares, and walks through the ones God opens.",
                anchor: "What door are you forcing open that you should pray about?",
                arrow: "Pray for one open door today instead of forcing it."),
            DayData(week: 4, theme: "Faithful Brothers", scripture: "Colossians 4:7-9",
                devotional: "Tychicus is a dear brother and faithful servant. Paul's letters end with names. Real people. The rooted life is surrounded by faithful men.",
                anchor: "Name your faithful brothers. If you cannot, that is your next priority.",
                arrow: "Reach out to a faithful brother today."),
            DayData(week: 4, theme: "Roots and Fruit", scripture: "Colossians 1:10",
                devotional: "Live a life worthy of the Lord, bearing fruit in every good work. Fruit in every good work. Not just at church. Everywhere.",
                anchor: "What fruit has this journey produced?",
                arrow: "Bear fruit in one specific area today."),
            DayData(week: 4, theme: "Built Up in Him", scripture: "Colossians 2:7",
                devotional: "Rooted and built up in Him, overflowing with thankfulness. Rooted. Built. Strengthened. Overflowing. That is the progression. You came in rooting. You leave built up.",
                anchor: "How have you been built up over these 30 days?",
                arrow: "Overflow with thankfulness today."),
            DayData(week: 4, theme: "Hold Together", scripture: "Colossians 1:17",
                devotional: "In Him all things hold together. Everything that feels fragmented, disconnected, or falling apart, He holds together. Including you. Especially you.",
                anchor: "What needs to be held together in your life right now?",
                arrow: "Let Christ hold it together today. Stop trying to glue it yourself."),
            DayData(week: 4, theme: "The Colossians Commission", scripture: "Colossians 4:17",
                devotional: "See to it that you complete the ministry you have received in the Lord. You have received a ministry. Not someday. Now. See to it that you complete it.",
                anchor: "What ministry has the Lord given you? Are you completing it?",
                arrow: "Take one step toward completing your ministry today."),
        ])
    }

    static func forgedInFireDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "Count It All Joy", scripture: "James 1:2-4",
                devotional: "Consider it pure joy when you face trials. Joy in trials is supernatural. The blacksmith does not hate the metal. He heats it because he sees what it can become.",
                anchor: "What trial are you in? Can you see any purpose?",
                arrow: "Choose joy in one difficult circumstance today."),
            DayData(week: 1, theme: "The Refiner's Fire", scripture: "Malachi 3:3",
                devotional: "He will sit as a refiner of silver. The refiner keeps the silver in the hottest part of the flame until he sees his own reflection. God keeps you in the fire until He sees His image in you.",
                anchor: "What impurity is God burning away?",
                arrow: "Submit to the refining process today."),
            DayData(week: 1, theme: "Suffering Produces Character", scripture: "Romans 5:3-5",
                devotional: "Suffering produces perseverance; perseverance, character; character, hope. The chain is unbreakable. You cannot skip steps. Character comes from endurance under pressure.",
                anchor: "Where in this chain are you right now?",
                arrow: "Endure one more hour in your difficulty. Perseverance is being built."),
            DayData(week: 1, theme: "Tested by Fire", scripture: "1 Peter 1:7",
                devotional: "The proven genuineness of your faith is of greater worth than gold. Gold is purified by fire. Your faith is purified the same way. Your proven faith is worth more than anything money can buy.",
                anchor: "Is your faith being proven genuine or cracking?",
                arrow: "Let your faith be proven today. Trust the refiner."),
            DayData(week: 1, theme: "The God of All Comfort", scripture: "2 Corinthians 1:3-4",
                devotional: "The God of all comfort, who comforts us so we can comfort those in any trouble. Your suffering is not wasted. The comfort God gives you becomes the comfort you give others.",
                anchor: "How has past suffering equipped you to comfort others?",
                arrow: "Comfort someone from experience today, not just advice."),
            DayData(week: 1, theme: "When God Seems Silent", scripture: "Psalm 22:1-2",
                devotional: "My God, why have you forsaken me? Even David felt God's silence. Even Jesus quoted this psalm on the cross. Silence is not absence. The refiner watches even when the silver cannot see him.",
                anchor: "Does God feel silent right now?",
                arrow: "Talk to God today even if He feels silent."),
            DayData(week: 1, theme: "Endurance Rewarded", scripture: "James 1:12",
                devotional: "Blessed is the one who perseveres under trial. There is a crown waiting. Not for the man who avoided suffering but for the man who endured it. Keep standing.",
                anchor: "What would standing the test look like for you?",
                arrow: "Stand one more day. The crown is ahead."),
            DayData(week: 2, theme: "The Pruning", scripture: "John 15:2",
                devotional: "Every branch that bears fruit He prunes so it will be even more fruitful. Pruning hurts. God cuts away good things to make room for better things.",
                anchor: "What has God pruned from your life recently?",
                arrow: "Cooperate with one area of pruning today."),
            DayData(week: 2, theme: "Thorns and Grace", scripture: "2 Corinthians 12:7-9",
                devotional: "My grace is sufficient for you. Paul prayed three times for the thorn to be removed. God said no and gave grace instead. Sometimes God does not remove the trial. He gives strength to endure it.",
                anchor: "What thorn have you been asking God to remove?",
                arrow: "Accept grace for your thorn today instead of demanding removal."),
            DayData(week: 2, theme: "Strength in Weakness", scripture: "2 Corinthians 12:10",
                devotional: "When I am weak, then I am strong. Your weakness is not a liability. It is the location of God's power. Stop hiding your weakness. Offer it to God.",
                anchor: "What weakness are you hiding?",
                arrow: "Admit one weakness to God today and ask Him to fill it."),
            DayData(week: 2, theme: "The Furnace of Affliction", scripture: "Isaiah 48:10",
                devotional: "I have tested you in the furnace of affliction. God chose the furnace. Not because He is cruel but because He knows what you can become. The furnace is where champions are made.",
                anchor: "Can you accept that God chose this furnace for your refinement?",
                arrow: "Walk through today's fire knowing God chose it and is in it."),
            DayData(week: 2, theme: "Patient Endurance", scripture: "James 5:10-11",
                devotional: "You have heard of Job's perseverance and seen what the Lord brought about. Job's story did not end in the ash heap. It ended with double restoration. Between suffering and restoration is patient endurance.",
                anchor: "Are you in the middle of your Job story?",
                arrow: "Practice patience today. The Lord is compassionate."),
            DayData(week: 2, theme: "The Discipline of Suffering", scripture: "Hebrews 12:11",
                devotional: "No discipline seems pleasant at the time, but later it produces a harvest of righteousness. The key phrase: trained BY it. The athlete who embraces pain becomes the champion.",
                anchor: "Are you being trained by your suffering or just enduring it?",
                arrow: "Look for the lesson in today's difficulty."),
            DayData(week: 2, theme: "Sharing in His Sufferings", scripture: "Philippians 3:10",
                devotional: "I want to know Christ and participation in His sufferings. Paul wanted the suffering too. Because suffering is where you know Christ most intimately.",
                anchor: "How has suffering brought you closer to Christ?",
                arrow: "Embrace one difficulty today as participation in Christ's sufferings."),
            DayData(week: 3, theme: "Beauty from Ashes", scripture: "Isaiah 61:3",
                devotional: "A crown of beauty instead of ashes. God specializes in transformation. Ashes to beauty. Mourning to gladness. Whatever has been burned, God can make something beautiful from the remains.",
                anchor: "What ashes might God transform into beauty?",
                arrow: "Offer your ashes to God today."),
            DayData(week: 3, theme: "Pressed but Not Crushed", scripture: "2 Corinthians 4:8-9",
                devotional: "Hard pressed but not crushed. Perplexed but not in despair. Every blow has a limit. There is a boundary around your suffering that the enemy cannot cross. God holds the line.",
                anchor: "Where are you being pressed? Can you trust the boundary?",
                arrow: "Hold the line today. You are pressed but not crushed."),
            DayData(week: 3, theme: "Momentary Troubles", scripture: "2 Corinthians 4:17",
                devotional: "Our light and momentary troubles are achieving an eternal glory that far outweighs them all. Compared to eternal glory, every earthly suffering is light.",
                anchor: "How does an eternal perspective change your view of current trouble?",
                arrow: "View one difficulty through an eternal lens today."),
            DayData(week: 3, theme: "God's Purposes in Pain", scripture: "Genesis 50:20",
                devotional: "You intended to harm me, but God intended it for good. Joseph endured thirteen years of suffering and God turned every bit into a rescue mission.",
                anchor: "What painful experience might God be turning into rescue for others?",
                arrow: "Trust that God is working your pain for good today."),
            DayData(week: 3, theme: "The Scars of Christ", scripture: "John 20:27",
                devotional: "See my hands. The risen Christ still had scars. He did not erase them. He displayed them. Your scars are evidence that you survived. Do not hide them.",
                anchor: "What scars are you hiding that could become testimony?",
                arrow: "Share one scar today with someone who needs to know survival is possible."),
            DayData(week: 3, theme: "The Comforter Comes", scripture: "John 14:16-17",
                devotional: "I will give you another advocate to be with you forever. In the fire you are not alone. The Holy Spirit is with you. The fire that surrounds you cannot touch the One who dwells within.",
                anchor: "Are you aware of the Holy Spirit's presence in your suffering?",
                arrow: "Invite the Comforter into your specific pain today."),
            DayData(week: 3, theme: "Weeping Endures a Night", scripture: "Psalm 30:5",
                devotional: "Weeping may stay for the night, but rejoicing comes in the morning. The night is real. The weeping is real. But it has an expiration date. Morning is coming.",
                anchor: "How long has your night been? Can you believe morning is coming?",
                arrow: "Hold on for one more night. Joy is coming."),
            DayData(week: 4, theme: "A Living Hope", scripture: "1 Peter 1:3",
                devotional: "He has given us new birth into a living hope through the resurrection. Your hope is not wishful thinking. It is living, active, rooted in resurrection power.",
                anchor: "Is your hope living or dead?",
                arrow: "Act on your living hope today."),
            DayData(week: 4, theme: "Refined as Gold", scripture: "Job 23:10",
                devotional: "When He has tested me, I will come forth as gold. Job could not see God or understand the plan. But he believed: when this is over, I will be gold.",
                anchor: "Do you believe you will come forth as gold?",
                arrow: "Walk through today's fire believing you will come forth refined."),
            DayData(week: 4, theme: "The Testimony of Fire", scripture: "Daniel 3:25",
                devotional: "I see four men in the fire, unbound and unharmed. The fourth man showed up IN the fire, not before it. Sometimes God's presence is most visible in the flames.",
                anchor: "Have you encountered God's presence inside your fire?",
                arrow: "Look for the fourth man today. He is in the fire with you."),
            DayData(week: 4, theme: "New Every Morning", scripture: "Lamentations 3:22-23",
                devotional: "His compassions never fail. They are new every morning. Jeremiah wrote this while watching Jerusalem burn. If he can find hope in destruction, you can find hope.",
                anchor: "What new mercy do you need tomorrow morning?",
                arrow: "Close today knowing tomorrow brings fresh compassion."),
            DayData(week: 4, theme: "From Ashes to Altar", scripture: "Romans 12:1",
                devotional: "Offer your bodies as a living sacrifice. The fire does not destroy you. It prepares you for the altar. You came in raw. You leave forged. Offer yourself.",
                anchor: "What has the forge produced in you?",
                arrow: "Offer yourself to God today. Forged, refined, ready."),
            DayData(week: 4, theme: "Forged and Sent", scripture: "Isaiah 6:8",
                devotional: "Whom shall I send? And I said, Here am I. Send me. Isaiah was forged by the vision of God's holiness. His lips were touched with fire. You have been in the furnace. Now will you go?",
                anchor: "Where is God sending you now that the fire has shaped you?",
                arrow: "Say Send me to God today."),
            DayData(week: 4, theme: "Unquenchable", scripture: "Isaiah 43:2",
                devotional: "When you walk through the fire, you will not be burned. The fire cannot destroy what God has decided to preserve. You are unquenchable. Not because of your resilience but because of His protection.",
                anchor: "What has the fire failed to destroy in you? That is what God is preserving.",
                arrow: "Walk in the unquenchable confidence that God preserves what He forges."),
            DayData(week: 4, theme: "The Scar That Testifies", scripture: "Galatians 6:17",
                devotional: "I bear on my body the marks of Jesus. Paul carried physical scars from his ministry. Every scar told a story. Your scars, visible or invisible, are not signs of weakness. They are proof that you stood in the fire and did not break. Wear them with honor.",
                anchor: "What scar has become a testimony of God's faithfulness?",
                arrow: "Let one scar speak today. Share it with someone who needs to know the fire does not have the last word."),
            DayData(week: 4, theme: "The Forge Complete", scripture: "James 1:4",
                devotional: "Let perseverance finish its work so that you may be mature and complete, not lacking anything. Perseverance has done its work. You are more mature, more complete than when you started. The forge is not punishment. It is promotion.",
                anchor: "How are you more complete now than 30 days ago?",
                arrow: "Walk out of the forge today. Mature, complete, forged. Ready for whatever comes next."),
        ])
    }

    static func theSentLifeDays() -> [JourneyDay] {
        build([
            DayData(week: 1, theme: "You Are Sent", scripture: "John 20:21",
                devotional: "As the Father has sent me, I am sending you. Every believer is sent. Not just missionaries. You. The man at the desk, on the job site, in the carpool line. You are on mission.",
                anchor: "Do you see yourself as sent?",
                arrow: "Walk into your day as a sent man today."),
            DayData(week: 1, theme: "The Great Commission", scripture: "Matthew 28:19-20",
                devotional: "Go and make disciples of all nations. Disciples, not converts. Not people who said a prayer and moved on. People being transformed, trained, and sent.",
                anchor: "Are you making disciples or just attending church?",
                arrow: "Invest in one person's spiritual growth today."),
            DayData(week: 1, theme: "The Power to Go", scripture: "Acts 1:8",
                devotional: "You will receive power when the Holy Spirit comes. The sent life is powered by the Spirit, not willpower. Your job is to show up and be available.",
                anchor: "Are you relying on your power or the Spirit's?",
                arrow: "Ask the Holy Spirit to empower one action today."),
            DayData(week: 1, theme: "Witnesses, Not Lawyers", scripture: "Acts 4:20",
                devotional: "We cannot help speaking about what we have seen and heard. A witness tells what happened. You do not need a seminary degree. You need a story.",
                anchor: "What has God done in your life that you can witness to?",
                arrow: "Share one piece of your testimony today."),
            DayData(week: 1, theme: "Wherever You Are", scripture: "Acts 17:26-27",
                devotional: "He marked out their appointed times and boundaries so that people might seek Him. God placed you where you are on purpose. Your neighborhood, your workplace. You are there on assignment.",
                anchor: "Where has God placed you on assignment?",
                arrow: "See your environment as a mission field today."),
            DayData(week: 1, theme: "Bold and Unhindered", scripture: "Acts 28:31",
                devotional: "He proclaimed the kingdom with all boldness and without hindrance. Acts ends mid-sentence. The story is not over. Acts continues through you.",
                anchor: "What would boldness look like in your life today?",
                arrow: "Do one bold thing for the kingdom today."),
            DayData(week: 1, theme: "The First Church", scripture: "Acts 2:42-47",
                devotional: "They devoted themselves to teaching, fellowship, breaking of bread, and prayer. Everyone was filled with awe. The first church was devoted people living radically together.",
                anchor: "How does your community compare to Acts 2?",
                arrow: "Practice one element of Acts 2 today."),
            DayData(week: 2, theme: "Go to Your Neighbor", scripture: "Luke 10:27-37",
                devotional: "Who is my neighbor? Everyone passed by had a reason not to stop. The sent man stops. He crosses the road. He gets his hands dirty.",
                anchor: "Who have you been walking past?",
                arrow: "Stop for one person today. Cross the road."),
            DayData(week: 2, theme: "Serve the Least", scripture: "Matthew 25:40",
                devotional: "Whatever you did for the least of these, you did for me. When you serve the overlooked, you serve Christ Himself.",
                anchor: "Who are the least in your world?",
                arrow: "Serve one overlooked person today as serving Christ."),
            DayData(week: 2, theme: "Ready to Give an Answer", scripture: "1 Peter 3:15",
                devotional: "Always be prepared to give the reason for your hope. With gentleness and respect. Preparation plus gentleness. Know why you believe. Deliver it with respect.",
                anchor: "Could you explain your hope if asked today?",
                arrow: "Prepare a 30-second version of your testimony."),
            DayData(week: 2, theme: "Plant and Water", scripture: "1 Corinthians 3:6",
                devotional: "I planted, Apollos watered, but God made it grow. You might not see the harvest. You might only plant a seed. Do not measure your mission by immediate results.",
                anchor: "What seeds are you planting?",
                arrow: "Plant one seed today and trust God with the growth."),
            DayData(week: 2, theme: "Ambassadors for Christ", scripture: "2 Corinthians 5:20",
                devotional: "We are Christ's ambassadors. An ambassador does not speak his own message. He represents the King. You carry the authority of heaven into every room.",
                anchor: "Are you representing Christ or yourself?",
                arrow: "Be Christ's ambassador in one interaction today."),
            DayData(week: 2, theme: "The Harvest is Plentiful", scripture: "Matthew 9:37-38",
                devotional: "The harvest is plentiful but the workers are few. There is no shortage of people who need God. There is a shortage of people willing to go.",
                anchor: "Are you a worker or a spectator?",
                arrow: "Pray for more workers today, then be one yourself."),
            DayData(week: 2, theme: "Sent with Nothing", scripture: "Luke 10:4",
                devotional: "Do not take a purse or bag or sandals. Jesus sent them with nothing. Complete dependence on God. When you have nothing, you discover He is everything.",
                anchor: "What are you holding onto that prevents full dependence on God?",
                arrow: "Let go of one crutch today and depend entirely on God."),
            DayData(week: 3, theme: "Persecution and Joy", scripture: "Acts 5:41",
                devotional: "They left rejoicing because they had been counted worthy of suffering for the Name. The cost is a badge of honor, not a mark of failure.",
                anchor: "Have you ever suffered for your faith?",
                arrow: "Do not shrink back from identifying with Christ today."),
            DayData(week: 3, theme: "Doors God Opens", scripture: "Revelation 3:8",
                devotional: "I have placed before you an open door that no one can shut. Your job is not to force doors. It is to walk through the ones God opens.",
                anchor: "What door has God opened that you have not walked through?",
                arrow: "Walk through one open door today."),
            DayData(week: 3, theme: "The Ministry of Reconciliation", scripture: "2 Corinthians 5:18",
                devotional: "God gave us the ministry of reconciliation. You are sent to reconcile. To bring people back to God. To restore broken relationships.",
                anchor: "Where is reconciliation needed in your world?",
                arrow: "Be a reconciler today. Bridge one gap."),
            DayData(week: 3, theme: "Compelled by Love", scripture: "2 Corinthians 5:14",
                devotional: "Christ's love compels us. The sent life is not motivated by guilt or duty. It is motivated by love. If your mission feels like a burden, you have lost the love.",
                anchor: "Is your spiritual activity driven by guilt or love?",
                arrow: "Do one thing today purely because you love God and people."),
            DayData(week: 3, theme: "The Fragrance of Christ", scripture: "2 Corinthians 2:14-15",
                devotional: "We are to God the pleasing aroma of Christ. You carry a fragrance. Not cologne but Christ. Wherever you go, people sense something different.",
                anchor: "What aroma does your life carry?",
                arrow: "Carry the fragrance of Christ into one environment today."),
            DayData(week: 3, theme: "Faithful in Little", scripture: "Luke 16:10",
                devotional: "Whoever can be trusted with very little can be trusted with much. Before God gives you a big mission, He tests you in small ones.",
                anchor: "What small mission is right in front of you?",
                arrow: "Be faithful in one small mission today."),
            DayData(week: 3, theme: "Sent Together", scripture: "Mark 6:7",
                devotional: "He sent them out two by two. Jesus never sent anyone alone. The sent life is communal. Lone rangers burn out. Brothers on mission sustain each other.",
                anchor: "Are you on mission alone or with brothers?",
                arrow: "Invite one brother into your mission today."),
            DayData(week: 4, theme: "Go and Tell", scripture: "Mark 16:15",
                devotional: "Go into all the world and preach the gospel. Your all the world might be your cul-de-sac. The world changes one conversation at a time.",
                anchor: "Who in your immediate world needs to hear the gospel from you?",
                arrow: "Share one truth about Christ with one person today."),
            DayData(week: 4, theme: "Make Disciples", scripture: "Matthew 28:19",
                devotional: "Go and make disciples. Not converts. A disciple changes their life. Making disciples requires time, investment, and patience.",
                anchor: "Are you making disciples or just converts?",
                arrow: "Take one discipleship step with someone today."),
            DayData(week: 4, theme: "Teach Them to Obey", scripture: "Matthew 28:20",
                devotional: "Teaching them to obey everything I have commanded. The Great Commission does not end at conversion. It ends at obedience. You can not teach what you are not living.",
                anchor: "What command are you teaching but not practicing?",
                arrow: "Obey one command you have been teaching today."),
            DayData(week: 4, theme: "I Am With You Always", scripture: "Matthew 28:20",
                devotional: "Surely I am with you always. The Great Commission ends with the greatest promise. Always. The One who sends you goes with you.",
                anchor: "Do you feel alone in your mission?",
                arrow: "Go with confidence today knowing Christ goes with you."),
            DayData(week: 4, theme: "Finish the Race", scripture: "Acts 20:24",
                devotional: "My only aim is to finish the race and complete the task. Paul did not value his own life above his mission. The sent life is about completing the task.",
                anchor: "What task has the Lord given you?",
                arrow: "Take one step toward completing your God-given task."),
            DayData(week: 4, theme: "Well Done", scripture: "Matthew 25:21",
                devotional: "Well done, good and faithful servant. This is the sentence every sent man wants to hear. Not well planned. Not well intentioned. Well done.",
                anchor: "If today were your last day, would God say well done?",
                arrow: "Live today so that well done would be the verdict."),
            DayData(week: 4, theme: "Sent and Sending", scripture: "2 Timothy 2:2",
                devotional: "Entrust to reliable people who will teach others. The ultimate sent life is not just going. It is sending others. You are a link in the chain.",
                anchor: "Who are you training to be sent?",
                arrow: "Identify one person to begin training for mission."),
            DayData(week: 4, theme: "The Unfinished Story", scripture: "Acts 28:31",
                devotional: "Boldly and without hindrance. Acts has no ending because the story is not over. You are writing the next chapter. Every day you anchor and loose your arrow, the story continues.",
                anchor: "What chapter are you writing in the ongoing story of Acts?",
                arrow: "Write one bold sentence in the story of God today."),
            DayData(week: 4, theme: "Go", scripture: "Matthew 28:19",
                devotional: "Go. One word. The simplest and hardest command Jesus ever gave. Not study more. Not plan more. Not wait until you feel ready. Go. You have been equipped. You have been sent. You have the Spirit. Go.",
                anchor: "What is stopping you from going?",
                arrow: "Go. Today. Right now. The world needs what you carry."),
        ])
    }
}

// swiftlint:enable file_length type_body_length
