// PromptLibrary+Extended.swift
// 190 additional anchor prompts + 193 additional arrow prompts
// Combined with the original 10+7 in Prompts.swift = 200 of each

import Foundation

// swiftlint:disable file_length line_length

extension PromptLibrary {

    // Compact tuple format for space efficiency
    private typealias AP = (String, PromptTheme, String, String, String, String)
    private typealias RP = (String, ArrowRole, String, String, String)

    // MARK: - Extra Anchor Prompts (190)
    static let extraAnchorPrompts: [AnchorPrompt] = extraAnchorData.map {
        AnchorPrompt(id: $0.0, theme: $0.1, scripture: $0.2, reference: $0.3, reflectionQuestion: $0.4, prayerStart: $0.5)
    }

    // MARK: - Extra Arrow Prompts (193)
    static let extraArrowPrompts: [ArrowPrompt] = extraArrowData.map {
        ArrowPrompt(id: $0.0, role: $0.1, question: $0.2, example: $0.3, verseReference: $0.4)
    }

    private static let extraAnchorData: [AP] = [
        // Watchful
        ("xa_011", .watchful, "Stay awake, for you do not know on what day your Lord is coming.", "Matthew 24:42", "If Christ returned today, what would He find you doing?", "Jesus, let me live today as if You are coming back tonight."),
        ("xa_012", .watchful, "Set a guard, O Lord, over my mouth.", "Psalm 141:3", "What words have you spoken this week that did not reflect Christ?", "Lord, guard my mouth today."),
        ("xa_013", .watchful, "The prudent sees danger and hides himself.", "Proverbs 22:3", "What danger are you walking toward that you are pretending does not exist?", "Father, give me wisdom to see the trap before I step in it."),
        ("xa_014", .watchful, "I will stand at my watch and station myself on the ramparts.", "Habakkuk 2:1", "Are you actively watching for God or just drifting?", "Lord, I take my position on the wall today."),
        ("xa_015", .watchful, "Let us not sleep, as others do, but let us keep awake.", "1 Thessalonians 5:6", "What part of your spiritual life has gone on autopilot?", "Wake me up, Lord. I refuse to sleepwalk through this life."),
        ("xa_016", .watchful, "Look carefully then how you walk, not as unwise but as wise.", "Ephesians 5:15", "Where are you being careless with your time or attention?", "God, make me deliberate today. Every step on purpose."),
        ("xa_017", .watchful, "Let anyone who thinks that he stands take heed lest he fall.", "1 Corinthians 10:12", "Where are you most confident in your own strength?", "Humble me, Lord. The moment I think I cannot fall is when I am most vulnerable."),
        ("xa_018", .watchful, "Examine yourselves, to see whether you are in the faith.", "2 Corinthians 13:5", "When did you last honestly assess your spiritual health?", "Lord, I submit to Your examination. Show me the truth."),
        ("xa_019", .watchful, "We must pay much closer attention, lest we drift away.", "Hebrews 2:1", "Where have you started drifting from what you know to be true?", "Lord, anchor me back."),
        ("xa_020", .watchful, "Awake, O sleeper, and arise from the dead, and Christ will shine on you.", "Ephesians 5:14", "What area of your life feels dead or dormant?", "Christ, shine on the dead places in me."),
        ("xa_021", .watchful, "Preparing your minds for action, being sober-minded.", "1 Peter 1:13", "Is your mind prepared for action today or are you mentally scattered?", "God, tighten my mind. No drifting today."),
        ("xa_022", .watchful, "Search me, O God, and know my heart! Try me and know my thoughts!", "Psalm 139:23", "Are you willing to let God search every corner of your heart?", "Search me, God. I hold nothing back."),
        ("xa_023", .watchful, "The night is far gone; the day is at hand. Let us cast off the works of darkness.", "Romans 13:12", "What works of darkness are you still carrying into the daylight?", "Lord, I strip off every weight. Today I walk in the light."),
        ("xa_024", .watchful, "Do not be deceived: God is not mocked.", "Galatians 6:7", "What seeds are you planting in your thoughts and habits? What harvest is coming?", "Father, make me sow wisely today."),
        ("xa_025", .watchful, "The wise man's eyes are in his head, but the fool walks in darkness.", "Ecclesiastes 2:14", "Are you walking with your eyes open today?", "Lord, give me eyes that see clearly."),

        // Stand Firm
        ("xa_026", .standFirm, "Therefore, my beloved brothers, be steadfast, immovable.", "1 Corinthians 15:58", "What is trying to move you from your position in Christ today?", "Lord, make me immovable in the things that matter."),
        ("xa_027", .standFirm, "Stand therefore, having fastened on the belt of truth.", "Ephesians 6:14", "Where are you believing or living a lie?", "God, truth is my foundation. Strip away every lie."),
        ("xa_028", .standFirm, "The Lord is my rock, my fortress, and my deliverer.", "Psalm 18:2", "What are you standing on today?", "You are my Rock, Lord. I build on nothing else."),
        ("xa_029", .standFirm, "Though a righteous man falls seven times, he rises again.", "Proverbs 24:16", "Are you beating yourself up for falling, or getting back up?", "Lord, I fell. I am getting up. Not because I am strong, but because You lift me."),
        ("xa_030", .standFirm, "He who began a good work in you will carry it on to completion.", "Philippians 1:6", "Do you believe God is still working in you?", "You started this work in me, Lord. I trust You to finish it."),
        ("xa_031", .standFirm, "He set my feet upon a rock, making my steps secure.", "Psalm 40:2", "Where do your steps feel insecure right now?", "Set my feet, Lord. You are the ground."),
        ("xa_032", .standFirm, "The steadfast love of the Lord never ceases.", "Lamentations 3:22", "Have you started believing God's patience with you has run out?", "Your mercies are new this morning, Lord."),
        ("xa_033", .standFirm, "The Lord is faithful. He will establish you and guard you.", "2 Thessalonians 3:3", "Where do you need the Lord to guard you today?", "You are faithful, Lord, even when I am not."),
        ("xa_034", .standFirm, "God is our refuge and strength, a very present help in trouble.", "Psalm 46:1", "Are you running to God or to other things for comfort?", "You are my refuge, God. Not my phone, not my habits. You."),
        ("xa_035", .standFirm, "Be strong and courageous. Do not be frightened.", "Joshua 1:9", "What are you afraid of today? Name it.", "I choose courage today, Lord. Not because I am brave, but because You are with me."),
        ("xa_036", .standFirm, "When I am afraid, I put my trust in you.", "Psalm 56:3", "Where does trust need to replace fear today?", "Lord, I am afraid. And I choose to trust You anyway."),
        ("xa_037", .standFirm, "Nothing can separate us from the love of God in Christ Jesus.", "Romans 8:38-39", "What feels like it is separating you from God's love? It is not.", "Nothing separates me from Your love, Lord."),
        ("xa_038", .standFirm, "Cast all your anxiety on him because he cares for you.", "1 Peter 5:7", "What anxiety are you carrying that God is asking you to hand over?", "I cast this anxiety on You, Lord."),
        ("xa_039", .standFirm, "The Lord will fight for you, and you have only to be silent.", "Exodus 14:14", "Where are you fighting battles God told you to let Him handle?", "Fight for me, Lord. I stop striving."),
        ("xa_040", .standFirm, "In this world you will have trouble. But take heart! I have overcome.", "John 16:33", "Where do you need Christ's peace today?", "I will have trouble, Lord. But You have overcome."),
        ("xa_041", .standFirm, "Wait for the Lord; be strong, and let your heart take courage.", "Psalm 27:14", "What are you impatient about?", "I wait for You, Lord. I will not rush ahead."),
        ("xa_042", .standFirm, "My flesh and my heart may fail, but God is the strength of my heart.", "Psalm 73:26", "Are you drawing from the right well?", "When my flesh fails, You are my strength."),
        ("xa_043", .standFirm, "In quietness and in trust shall be your strength.", "Isaiah 30:15", "Can you get quiet and trust today?", "Lord, I get quiet before You now."),
        ("xa_044", .standFirm, "Resist the devil, and he will flee from you.", "James 4:7-8", "What do you need to resist today?", "I resist the enemy. I draw near to You, God."),
        ("xa_045", .standFirm, "The righteous shall live by faith.", "Romans 1:17", "What decision requires faith instead of certainty?", "I live by faith today, Lord. Not by sight."),

        // Act Like Men
        ("xa_046", .actLikeMen, "When I became a man, I gave up childish ways.", "1 Corinthians 13:11", "What childish habits or excuses are you still holding onto?", "Lord, I am done with childish things. Grow me."),
        ("xa_047", .actLikeMen, "Show yourself in all respects to be a model of good works.", "Titus 2:7", "Who is watching your life right now? What example are you setting?", "God, let my life preach louder than my words."),
        ("xa_048", .actLikeMen, "Husbands, love your wives, as Christ loved the church.", "Ephesians 5:25", "How are you sacrificially loving those closest to you?", "Lord, show me what sacrificial love looks like in my home today."),
        ("xa_049", .actLikeMen, "Whoever would be great among you must be your servant.", "Matthew 20:26", "Where have you confused leadership with control?", "Lord, lower me. Not to weakness, but to service."),
        ("xa_050", .actLikeMen, "Have I not commanded you? Be strong and courageous.", "Joshua 1:9", "What courageous step are you avoiding?", "I choose courage, Lord. The step I have been afraid to take, I take it today."),
        ("xa_051", .actLikeMen, "Better is a patient man than a warrior.", "Proverbs 16:32", "What triggers your temper?", "Lord, I want to be the man who controls himself."),
        ("xa_052", .actLikeMen, "As iron sharpens iron, so one man sharpens another.", "Proverbs 27:17", "Who is sharpening you right now?", "Lord, send me a brother. And make me worth sharpening."),
        ("xa_053", .actLikeMen, "Each one should test his own work.", "Galatians 6:4", "Are you measuring yourself against other men or against God's calling?", "Lord, my only standard is Your calling on my life."),
        ("xa_054", .actLikeMen, "Train yourself for godliness.", "1 Timothy 4:7-8", "Do you train your soul as hard as your body?", "Lord, I train for godliness today."),
        ("xa_055", .actLikeMen, "Do it with all your might.", "Ecclesiastes 9:10", "What task deserves your full effort today?", "I give my full effort today, Lord. No coasting."),
        ("xa_056", .actLikeMen, "The way of a fool is right in his own eyes.", "Proverbs 12:15", "When did you last genuinely listen to correction?", "Make me teachable, Lord."),
        ("xa_057", .actLikeMen, "A good name is more desirable than great riches.", "Proverbs 22:1", "When people say your name, what comes to mind?", "Lord, build my character. My reputation will follow."),
        ("xa_058", .actLikeMen, "He must manage his own household well.", "1 Timothy 3:4", "Are the people closest to you flourishing?", "God, before I lead anywhere else, help me lead well at home."),
        ("xa_059", .actLikeMen, "The faithful man will abound with blessings.", "Proverbs 28:20", "What does faithfulness look like in the small things today?", "Lord, make me faithful in the small things."),
        ("xa_060", .actLikeMen, "A righteous man who walks in his integrity.", "Proverbs 20:7", "Your integrity today is your children's inheritance tomorrow.", "Lord, let me walk in integrity today."),

        // Be Strong
        ("xa_061", .beStrong, "I can do all things through him who strengthens me.", "Philippians 4:13", "What do you need strength to endure today?", "Strengthen me for what is ahead, Lord."),
        ("xa_062", .beStrong, "The Lord is my light and my salvation; whom shall I fear?", "Psalm 27:1", "Name your fear. Now hold it against God's sovereignty.", "Lord, You are my light. I will not fear."),
        ("xa_063", .beStrong, "Those who hope in the Lord will renew their strength.", "Isaiah 40:31", "Are you running on empty or drawing from the right source?", "Lord, I wait on You. Renew my strength."),
        ("xa_064", .beStrong, "God gave us a spirit not of fear but of power and love and self-control.", "2 Timothy 1:7", "Fear is not from God. Which do you need most today: power, love, or self-control?", "I reject the spirit of fear. I walk in power and love today."),
        ("xa_065", .beStrong, "Be strong and let your heart take courage.", "Psalm 31:24", "Where does courage need to override your hesitation?", "Lord, give my heart courage."),
        ("xa_066", .beStrong, "Mighty warrior, the Lord is with you!", "Judges 6:12", "God sees what you can become, not just what you are.", "Lord, You call me a warrior when I feel like a coward."),
        ("xa_067", .beStrong, "Do not fear, for I am with you. I will strengthen you and help you.", "Isaiah 41:10", "Which promise do you need to claim today?", "You are with me. You will strengthen me. I believe it."),
        ("xa_068", .beStrong, "Not by might, nor by power, but by my Spirit.", "Zechariah 4:6", "Where are you relying on might when you need the Spirit?", "Not by my might, Lord. By Your Spirit."),
        ("xa_069", .beStrong, "My grace is sufficient for you, for my power is made perfect in weakness.", "2 Corinthians 12:9", "Can you stop fighting your weakness and let God fill it?", "I am weak, Lord. And that is where Your power is made perfect."),
        ("xa_070", .beStrong, "He gives power to the faint.", "Isaiah 40:29", "Are you faint today? God empowers the weary.", "I am faint, Lord. Increase my strength."),
        ("xa_071", .beStrong, "The joy of the Lord is your strength.", "Nehemiah 8:10", "When did you last experience genuine joy in God?", "Lord, let Your joy be my strength today."),
        ("xa_072", .beStrong, "We do not lose heart. Inwardly we are being renewed day by day.", "2 Corinthians 4:16", "Are you being renewed today?", "Renew me inwardly today, Lord."),
        ("xa_073", .beStrong, "I sought the Lord, and he answered me; he delivered me from all my fears.", "Psalm 34:4", "Have you actually sought the Lord about what you fear?", "I seek You now, Lord. Deliver me from every fear."),
        ("xa_074", .beStrong, "Blessed is the man who remains steadfast under trial.", "James 1:12", "What is your trial revealing about who you really are?", "Lord, I remain steadfast."),
        ("xa_075", .beStrong, "Even though I walk through the valley of the shadow of death, I will fear no evil.", "Psalm 23:4", "The shadow of death is just a shadow. God is with you.", "I walk through this valley, Lord. And You are with me."),
        ("xa_076", .beStrong, "For the battle is the Lord's.", "1 Samuel 17:47", "The outcome is already decided. You fight FROM victory.", "The battle is Yours, Lord."),
        ("xa_077", .beStrong, "He who is in you is greater than he who is in the world.", "1 John 4:4", "The One inside you is greater than whatever you face today.", "Greater is He who is in me."),
        ("xa_078", .beStrong, "You will keep in perfect peace those whose minds are steadfast.", "Isaiah 26:3", "Is your mind steadfast or scattered today?", "Fix my mind on You, Lord."),
        ("xa_079", .beStrong, "Fear not, for I have redeemed you; I have called you by name.", "Isaiah 43:1", "You are redeemed, named, and claimed. Live like it.", "I am Yours, Lord. Redeemed and named."),
        ("xa_080", .beStrong, "For I know the plans I have for you, declares the Lord.", "Jeremiah 29:11", "Can you trust the destination when the road is rough?", "Your plans are good, Lord."),

        // In Love
        ("xa_081", .inLove, "Let all that you do be done in love.", "1 Corinthians 16:14", "How will you lead with love today?", "Lord, let everything I do flow from love."),
        ("xa_082", .inLove, "Love is patient and kind; it does not envy or boast.", "1 Corinthians 13:4", "Where have you been impatient or unkind this week?", "Lord, make my love patient and kind."),
        ("xa_083", .inLove, "Greater love has no one than this: to lay down his life.", "John 15:13", "What can you sacrifice today?", "Lord, show me where to lay something down for love."),
        ("xa_084", .inLove, "Above all, keep loving one another earnestly.", "1 Peter 4:8", "Who do you need to cover with love instead of judgment?", "Help me cover others with love today, Lord."),
        ("xa_085", .inLove, "Love your enemies and pray for those who persecute you.", "Matthew 5:44", "Who is hardest for you to love right now?", "Lord, love this person through me."),
        ("xa_086", .inLove, "We love because he first loved us.", "1 John 4:19", "Do you really believe God loves you?", "You loved me first, Lord. That is where my love comes from."),
        ("xa_087", .inLove, "Love does no wrong to a neighbor.", "Romans 13:10", "Are your words and actions doing good or harm?", "Lord, let my love be felt, not just spoken."),
        ("xa_088", .inLove, "But God shows his love for us in that while we were still sinners, Christ died.", "Romans 5:8", "Can you extend that same love to someone who has not earned it?", "You loved me at my worst, God. Help me love others at theirs."),
        ("xa_089", .inLove, "Be kind to one another, tenderhearted, forgiving.", "Ephesians 4:32", "Who do you need to forgive today?", "I forgive, Lord. Not because it is easy, but because You forgave me first."),
        ("xa_090", .inLove, "By this all people will know you are my disciples: if you have love.", "John 13:35", "The world knows you by your love, not your arguments.", "Lord, let my love be my loudest sermon today."),
        ("xa_091", .inLove, "There is no fear in love, but perfect love casts out fear.", "1 John 4:18", "Where is fear driving your behavior instead of love?", "Cast out my fear with Your perfect love, Lord."),
        ("xa_092", .inLove, "Let us not love in word or talk but in deed and in truth.", "1 John 3:18", "What would it look like to love with action today?", "Lord, my love today will have hands and feet."),
        ("xa_093", .inLove, "Dear friends, since God so loved us, we also ought to love one another.", "1 John 4:11", "The logic is simple: God loved you, so love others.", "Your love to me overflows to others, Lord."),
        ("xa_094", .inLove, "Walk in love, as Christ loved us and gave himself up for us.", "Ephesians 5:2", "Every step is an opportunity to love.", "I walk in love today, Lord. Every step."),
        ("xa_095", .inLove, "Keep yourselves in the love of God.", "Jude 1:21", "Staying in God's love requires intentionality.", "I keep myself in Your love today, Lord."),

        // Surrender
        ("xa_096", .surrender, "Not my will, but yours, be done.", "Luke 22:42", "Can you pray this in your darkest hour?", "Not my will, but Yours, Lord."),
        ("xa_097", .surrender, "Come to me, all who labor and are heavy laden.", "Matthew 11:28", "What burden are you carrying that was never yours?", "I come to You, Jesus. Give me rest."),
        ("xa_098", .surrender, "Whoever finds his life will lose it, and whoever loses his life for my sake will find it.", "Matthew 10:39", "What are you gripping so tightly that it is killing you?", "I lose my life for Your sake, Lord."),
        ("xa_099", .surrender, "Trust in the Lord with all your heart.", "Proverbs 3:5", "How much of your life is based on your understanding vs God's?", "I trust You with my whole heart today, Lord."),
        ("xa_100", .surrender, "If anyone would come after me, let him deny himself and take up his cross daily.", "Luke 9:23", "What does dying to yourself look like today?", "I pick up my cross today, Lord."),
        ("xa_101", .surrender, "Present your bodies as a living sacrifice.", "Romans 12:1", "What part of your life are you pulling back off the altar?", "I put myself back on the altar, Lord."),
        ("xa_102", .surrender, "He must increase, but I must decrease.", "John 3:30", "Where is your ego taking up space that belongs to God?", "Lord, increase in my life. I decrease."),
        ("xa_103", .surrender, "The sacrifices of God are a broken spirit.", "Psalm 51:17", "God wants your honesty, not your performance.", "I bring You my broken heart, Lord."),
        ("xa_104", .surrender, "Unless a grain of wheat falls and dies, it remains alone.", "John 12:24", "What needs to die for something greater to grow?", "Lord, let what needs to die fall to the ground."),
        ("xa_105", .surrender, "For to me, to live is Christ and to die is gain.", "Philippians 1:21", "Is Christ the center or a consultant?", "To live is Christ, Lord."),
        ("xa_106", .surrender, "Humble yourselves before the Lord, and he will exalt you.", "James 4:10", "Where is God asking you to go low today?", "I humble myself before You, Lord."),
        ("xa_107", .surrender, "Take my yoke upon you, and learn from me.", "Matthew 11:29", "His yoke is different from yours. His is light.", "I take Your yoke, Lord."),
        ("xa_108", .surrender, "Seek first the kingdom of God.", "Matthew 6:33", "What are you seeking first today?", "I seek Your kingdom first today, Lord."),
        ("xa_109", .surrender, "Delight yourself in the Lord, and he will give you the desires of your heart.", "Psalm 37:4", "When you delight in God, your desires change.", "I delight in You, Lord. Shape my desires."),
        ("xa_110", .surrender, "Let go, and know that I am God.", "Psalm 46:10", "What are you gripping with white knuckles right now?", "I let go, Lord. You are God. I am not."),

        // Armor
        ("xa_111", .armor, "Put on the whole armor of God.", "Ephesians 6:11", "Which piece of armor have you neglected?", "I put on Your full armor today, Lord."),
        ("xa_112", .armor, "Having put on the breastplate of righteousness.", "Ephesians 6:14", "Are you protecting your heart with righteousness?", "I put on righteousness, Lord. Guard my heart."),
        ("xa_113", .armor, "Above all, taking the shield of faith.", "Ephesians 6:16", "What fiery darts are flying at you today?", "I raise the shield of faith, Lord."),
        ("xa_114", .armor, "Take the helmet of salvation.", "Ephesians 6:17", "Your thought life is the battlefield.", "I put on the helmet of salvation, Lord. Guard my mind."),
        ("xa_115", .armor, "The sword of the Spirit, which is the word of God.", "Ephesians 6:17", "When did you last use Scripture to fight back?", "Your Word is my sword, Lord."),
        ("xa_116", .armor, "Praying at all times in the Spirit.", "Ephesians 6:18", "Prayer is the atmosphere the armor operates in.", "I pray in the Spirit today, Lord."),
        ("xa_117", .armor, "For though we walk in the flesh, we do not war according to the flesh.", "2 Corinthians 10:3", "Are you using the right weapons?", "Lord, I fight with spiritual weapons today."),
        ("xa_118", .armor, "The weapons of our warfare have divine power to destroy strongholds.", "2 Corinthians 10:4", "What stronghold needs to be demolished?", "I demolish this stronghold in Jesus' name."),
        ("xa_119", .armor, "We take every thought captive to obey Christ.", "2 Corinthians 10:5", "Every thought needs to be interrogated.", "I take this thought captive, Lord."),
        ("xa_120", .armor, "No weapon fashioned against you shall succeed.", "Isaiah 54:17", "The weapon may be formed but it will not prosper.", "No weapon formed against me will succeed."),
        ("xa_121", .armor, "The Lord is my rock and my fortress.", "2 Samuel 22:2", "Is the Lord your first line of defense?", "You are my fortress, Lord."),
        ("xa_122", .armor, "I have stored up your word in my heart.", "Psalm 119:11", "What verse can you draw on in battle?", "Your Word is in my heart, Lord. Ready to deploy."),
        ("xa_123", .armor, "For we do not wrestle against flesh and blood.", "Ephesians 6:12", "The battle is spiritual. Fight accordingly.", "I see the real enemy, Lord."),
        ("xa_124", .armor, "Fight the good fight of the faith.", "1 Timothy 6:12", "It is a good fight. Because you fight for something eternal.", "I fight the good fight today, Lord."),
        ("xa_125", .armor, "Thanks be to God, who gives us the victory.", "1 Corinthians 15:57", "You are fighting from victory, not toward it.", "The victory is already mine through Christ."),

        // Mixed themes (126-190)
        ("xa_126", .watchful, "Take no part in the unfruitful works of darkness, but instead expose them.", "Ephesians 5:11", "Is there anything in your life that thrives in darkness?", "Father, bring everything into the light."),
        ("xa_127", .standFirm, "The name of the Lord is a strong tower.", "Proverbs 18:10", "What do you run to when life gets hard?", "Lord, I run to You. Not to escape, but to be strengthened."),
        ("xa_128", .actLikeMen, "But you, man of God, pursue righteousness, godliness, faith, love.", "1 Timothy 6:11", "What do you need to flee from and what are you pursuing?", "I flee what destroys me. I pursue what God calls me to."),
        ("xa_129", .beStrong, "The Lord your God is in your midst, a mighty one who will save.", "Zephaniah 3:17", "God is not watching from a distance. He is in your midst.", "You are in my midst, Lord."),
        ("xa_130", .inLove, "Owe no one anything, except to love each other.", "Romans 13:8", "Who do you owe love to today?", "I owe love today, Lord."),
        ("xa_131", .surrender, "I have been crucified with Christ.", "Galatians 2:20", "The old you is dead. Stop resurrecting him.", "The old me is dead, Lord. Christ lives in me."),
        ("xa_132", .armor, "And having done all, to stand firm.", "Ephesians 6:13", "After everything, the instruction is: stand.", "I have done all, Lord. And now I stand."),
        ("xa_133", .watchful, "The thief comes only to steal and kill and destroy.", "John 10:10", "What is the enemy trying to steal from you right now?", "I reject the thief's agenda today, Lord."),
        ("xa_134", .standFirm, "My flesh and my heart may fail, but God is the strength of my heart.", "Psalm 73:26", "Your willpower will run out. God's will not.", "When my flesh fails, You are my strength."),
        ("xa_135", .actLikeMen, "The glory of young men is their strength.", "Proverbs 20:29", "How are you using your strength: for yourself or for others?", "God, direct my strength today."),
        ("xa_136", .beStrong, "For the Lord your God is he who goes with you to fight for you.", "Deuteronomy 20:4", "You are not fighting alone.", "You go before me, Lord."),
        ("xa_137", .inLove, "If I speak with tongues but have not love, I am a noisy gong.", "1 Corinthians 13:1", "Without love, it is all just noise.", "Do not let me be noise today, Lord."),
        ("xa_138", .surrender, "For we walk by faith, not by sight.", "2 Corinthians 5:7", "Where is God asking you to walk blind today?", "I walk by faith today, Lord."),
        ("xa_139", .armor, "The God of peace will soon crush Satan under your feet.", "Romans 16:20", "Victory comes from peace, not panic.", "God of peace, crush the enemy under my feet."),
        ("xa_140", .watchful, "For many walk as enemies of the cross of Christ.", "Philippians 3:18", "Who or what is subtly pulling you from the cross?", "Jesus, I cling to Your cross today."),
        ("xa_141", .standFirm, "In all these things we are more than conquerors.", "Romans 8:37", "You are not barely surviving. You are more than a conqueror.", "I am more than a conqueror, Lord."),
        ("xa_142", .actLikeMen, "Let a man examine himself.", "1 Corinthians 11:28", "When did you last honestly examine your motives?", "I examine myself before You, Lord."),
        ("xa_143", .beStrong, "Commit your way to the Lord; trust in him, and he will act.", "Psalm 37:5", "Have you actually committed your way or are you controlling the outcome?", "I commit today to You, Lord."),
        ("xa_144", .inLove, "And over all these virtues put on love.", "Colossians 3:14", "Love is the thread that holds every virtue together.", "Love is the thread, Lord. Weave it through everything today."),
        ("xa_145", .surrender, "And we know that for those who love God all things work together for good.", "Romans 8:28", "All things. Even this. Can you trust that?", "All things work together, Lord."),
        ("xa_146", .armor, "For the word of God is living and active, sharper than any sword.", "Hebrews 4:12", "The Word is not a reference book. It is a living weapon.", "Your Word is alive, Lord. I wield it today."),
        ("xa_147", .watchful, "I have set the Lord always before me.", "Psalm 16:8", "Is the Lord actually before you today or in the background?", "I set You before me right now, Lord."),
        ("xa_148", .standFirm, "Let us hold fast the confession of our hope without wavering.", "Hebrews 10:23", "Where is your hope wavering?", "I hold fast, Lord."),
        ("xa_149", .actLikeMen, "He who walks with the wise becomes wise.", "Proverbs 13:20", "Look at your five closest relationships.", "Lord, give me wisdom to choose my circle carefully."),
        ("xa_150", .beStrong, "The Lord is the stronghold of my life.", "Psalm 27:1", "Who can threaten a man whose life is fortified by God?", "You are the stronghold of my life, Lord."),
        ("xa_151", .inLove, "Hatred stirs up strife, but love covers all offenses.", "Proverbs 10:12", "What offense are you holding onto that love needs to cover?", "I let go of this offense, Lord."),
        ("xa_152", .surrender, "Count it all joy when you meet trials.", "James 1:2", "Joy in trials is choosing to trust God's purpose.", "I count this trial as joy, Lord."),
        ("xa_153", .armor, "Who shall bring any charge against God's elect? It is God who justifies.", "Romans 8:33", "The charges against you are dismissed.", "I am justified, Lord."),
        ("xa_154", .watchful, "Pay careful attention to yourselves and to all the flock.", "Acts 20:28", "Who else is depending on your watchfulness today?", "Father, let me guard others well."),
        ("xa_155", .standFirm, "The Lord is my strength and my song.", "Exodus 15:2", "Is the Lord your strength or are you trying to be your own?", "You are my strength and my song."),
        ("xa_156", .actLikeMen, "The Lord is a warrior; the Lord is his name.", "Exodus 15:3", "You are made in the image of a warrior God.", "I am a warrior, Lord, because You are."),
        ("xa_157", .beStrong, "The Lord is faithful in all his words.", "Psalm 145:13", "God is faithful in ALL His words. Not some. All.", "You are faithful, Lord. In every word."),
        ("xa_158", .inLove, "So now faith, hope, and love abide; the greatest is love.", "1 Corinthians 13:13", "Love is the only thing that outlasts this life.", "Lord, I invest in love today."),
        ("xa_159", .surrender, "Your kingdom come, your will be done.", "Matthew 6:10", "Your kingdom displacing mine. Your will overriding mine.", "Your kingdom come today, Lord."),
        ("xa_160", .armor, "Be strong in the Lord and in his mighty power.", "Ephesians 6:10", "The armor only works if you are strong in the Lord.", "I am strong in You, Lord."),
        ("xa_161", .watchful, "Do not let your hearts be troubled.", "John 14:1", "What is troubling your heart today? Bring it to God.", "Lord, I trust in You. My heart will not be troubled."),
        ("xa_162", .standFirm, "He is before all things, and in him all things hold together.", "Colossians 1:17", "Everything is held together by Christ.", "Lord, You hold all things together, including me."),
        ("xa_163", .actLikeMen, "Fathers, do not provoke your children to anger.", "Ephesians 6:4", "Are you leading your family or provoking them?", "Father, make me a father who leads with patience."),
        ("xa_164", .beStrong, "For the battle is not yours, but God's.", "2 Chronicles 20:15", "Step back and let God fight.", "This battle is Yours, God. I step back and trust."),
        ("xa_165", .inLove, "Husbands, love your wives. Do not be harsh with them.", "Colossians 3:19", "Harshness destroys what love builds.", "Lord, remove all harshness from my words today."),
        ("xa_166", .surrender, "In everything give thanks.", "1 Thessalonians 5:18", "Gratitude is a form of surrender.", "Thank You, Lord. In every circumstance."),
        ("xa_167", .armor, "In all circumstances take up the shield of faith.", "Ephesians 6:16", "ALL circumstances. Even the easy ones.", "In all circumstances, Lord. I raise the shield."),
        ("xa_168", .watchful, "Be on your guard; stand firm in the faith; be men of courage; be strong.", "1 Corinthians 16:13 NIV", "Four commands in one verse. Which one are you weakest in?", "Lord, I will be on guard, firm, courageous, and strong."),
        ("xa_169", .standFirm, "I will never leave you nor forsake you.", "Hebrews 13:5", "Whatever you face today, you face it with God.", "You have not abandoned me, Lord. You never will."),
        ("xa_170", .actLikeMen, "Plans fail for lack of counsel.", "Proverbs 15:22", "Are you making decisions alone?", "God, humble me enough to ask for counsel."),
        ("xa_171", .beStrong, "The Lord is my shepherd; I shall not want.", "Psalm 23:1", "He leads, provides, protects, and restores.", "You are my shepherd, Lord."),
        ("xa_172", .inLove, "A new commandment I give to you, that you love one another.", "John 13:34", "Love as Christ has loved you.", "Lord, I love others the way You love me."),
        ("xa_173", .surrender, "Deny yourself, take up your cross, and follow me.", "Matthew 16:24", "Following Jesus costs something.", "I deny myself today, Lord."),
        ("xa_174", .armor, "Thanks be to God, who always leads us in triumphal procession.", "2 Corinthians 2:14", "You are in a triumphal procession led by the King.", "Lead me in triumph today, Lord."),
        ("xa_175", .watchful, "Blessed are the pure in heart, for they shall see God.", "Matthew 5:8", "Purity of heart starts with what you allow in.", "Lord, purify my heart today."),
        ("xa_176", .standFirm, "The Lord is good, a stronghold in the day of trouble.", "Nahum 1:7", "When trouble comes, where do you run?", "You are my stronghold in trouble, Lord."),
        ("xa_177", .actLikeMen, "Do nothing out of selfish ambition.", "Philippians 2:3", "Check your motives today.", "Lord, strip away selfish ambition."),
        ("xa_178", .beStrong, "He makes my feet like the feet of a deer.", "Psalm 18:33", "God gives you surefooted strength for the high places.", "Make my feet steady, Lord."),
        ("xa_179", .inLove, "If I have all faith but have not love, I am nothing.", "1 Corinthians 13:2", "Faith without love is empty.", "Lord, love is the point. Not knowledge, not faith alone. Love."),
        ("xa_180", .surrender, "The Lord gave, and the Lord has taken away; blessed be the name of the Lord.", "Job 1:21", "Can you worship when He takes something away?", "Blessed be Your name, Lord."),
        ("xa_181", .armor, "Therefore take up the whole armor of God.", "Ephesians 6:13", "The evil day may be today. Are you dressed for it?", "I take up the whole armor, Lord."),
        ("xa_182", .watchful, "Your word is a lamp to my feet.", "Psalm 119:105", "The Word shows you the next step. Not the whole road.", "Your Word lights my path today, Lord."),
        ("xa_183", .standFirm, "My God is my rock, in whom I take refuge.", "2 Samuel 22:3", "He is your refuge. Stop looking for shelter elsewhere.", "I take refuge in You, Lord."),
        ("xa_184", .actLikeMen, "Do all things without grumbling.", "Philippians 2:14", "Your attitude speaks louder than your actions.", "Lord, remove the grumbling from my heart."),
        ("xa_185", .beStrong, "For nothing will be impossible with God.", "Luke 1:37", "What have you decided is impossible?", "Nothing is impossible with You, Lord."),
        ("xa_186", .inLove, "The greatest of these is love.", "1 Corinthians 13:13", "Love outlasts everything.", "Lord, love is my highest priority today."),
        ("xa_187", .surrender, "Take my yoke upon you and learn from me.", "Matthew 11:29", "Christ's yoke is easy because He carries it with you.", "I take Your yoke, Lord."),
        ("xa_188", .armor, "For the Lord God is a sun and shield.", "Psalm 84:11", "He illuminates and protects.", "You are my sun and shield, Lord."),
        ("xa_189", .watchful, "Let the word of Christ dwell in you richly.", "Colossians 3:16", "Is the Word dwelling in you or just passing through?", "Let Your Word dwell in me richly, Lord."),
        ("xa_190", .standFirm, "For God has not given us a spirit of fear, but of power.", "2 Timothy 1:7", "What you feel is not what He gave you.", "I walk in power, love, and self-control."),
        ("xa_191", .watchful, "For the Lord sees not as man sees: man looks on the outward appearance, but the Lord looks on the heart.", "1 Samuel 16:7", "What does God see when He looks at your heart today?", "Lord, look at my heart. See what I am hiding even from myself."),
        ("xa_192", .standFirm, "The Lord is a refuge for the oppressed, a stronghold in times of trouble.", "Psalm 9:9", "Where do you run when you feel overwhelmed?", "You are my refuge, Lord. Not my backup plan. My first response."),
        ("xa_193", .actLikeMen, "He has told you, O man, what is good: to do justice, to love kindness, and to walk humbly.", "Micah 6:8", "Justice, kindness, humility. Which one needs more of your attention today?", "Lord, show me what is good today. Justice, kindness, humility. All three."),
        ("xa_194", .beStrong, "But the Lord stood by me and strengthened me.", "2 Timothy 4:17", "Even when everyone else left, the Lord stood by Paul. He stands by you too.", "You stand by me, Lord. Even when others walk away."),
        ("xa_195", .inLove, "Beloved, if God so loved us, we also ought to love one another.", "1 John 4:11", "God's love toward you creates an obligation to love others.", "Your love overflows through me to others, Lord."),
        ("xa_196", .surrender, "The Lord is my portion, says my soul, therefore I will hope in him.", "Lamentations 3:24", "Is the Lord your portion, or are you still looking for satisfaction elsewhere?", "You are my portion, Lord. I need nothing else."),
        ("xa_197", .armor, "Stand firm then, with the belt of truth buckled around your waist.", "Ephesians 6:14 NIV", "Truth is the belt that holds everything together. Without it, the armor falls apart.", "I buckle truth around me today, Lord. Everything else hangs on this."),
        ("xa_198", .watchful, "Therefore encourage one another and build each other up.", "1 Thessalonians 5:11", "Who needs your encouragement today? Do not wait for them to ask.", "Lord, show me who needs a word of life from me today."),
        ("xa_199", .standFirm, "The eternal God is your refuge, and underneath are the everlasting arms.", "Deuteronomy 33:27", "Underneath every fall, every failure, every fear are His everlasting arms.", "Your arms are underneath me, Lord. I cannot fall beyond Your reach."),
        ("xa_200", .actLikeMen, "Be strong, and let us show ourselves courageous for the sake of our people.", "2 Samuel 10:12", "Your courage is not just for you. It is for everyone who depends on you.", "Lord, I am courageous for the sake of those You gave me."),
    ]

    private static let extraArrowData: [RP] = [
        // Servant Leader (1-38)
        ("xr_001", .servantLeader, "Where did you serve without recognition today?", "Made breakfast for the family. Covered a shift. Cleaned up without mentioning it.", "Matthew 6:3-4"),
        ("xr_002", .servantLeader, "How did you put someone else first today?", "Stayed late to help a team member. Gave up my seat. Drove someone who needed a ride.", "Philippians 2:3-4"),
        ("xr_003", .servantLeader, "What task below your status did you take on today?", "Took out the trash. Mopped the floor. Changed a diaper without being asked.", "John 13:14"),
        ("xr_004", .servantLeader, "How did you lead by example today?", "Showed up early. Did the work before delegating. Admitted my mistake first.", "1 Peter 5:3"),
        ("xr_005", .servantLeader, "Where did you choose patience over efficiency today?", "Let my kid explain slowly. Listened to a long story. Waited without rushing.", "1 Thessalonians 5:14"),
        ("xr_006", .servantLeader, "What sacrifice did you make at home that nobody noticed?", "Made dinner after a long day. Fixed something broken. Handled a bill quietly.", "Colossians 3:23-24"),
        ("xr_007", .servantLeader, "How did you make someone feel valued today?", "Made eye contact. Asked a follow-up question. Remembered something they told me.", "Romans 12:10"),
        ("xr_008", .servantLeader, "What did you give up so someone else could have what they needed?", "Gave up my lunch break. Let someone go ahead. Shared credit for an idea.", "Acts 20:35"),
        ("xr_009", .servantLeader, "How did you show up for your family beyond what was expected?", "Left work early. Put my phone down during dinner. Read an extra bedtime story.", "1 Timothy 5:8"),
        ("xr_010", .servantLeader, "What inconvenience did you accept to serve someone?", "Drove across town. Rearranged my schedule. Stayed when I wanted to leave.", "Galatians 5:13"),
        ("xr_011", .servantLeader, "How did you advocate for someone who could not advocate for themselves?", "Spoke up for a colleague. Defended someone being gossiped about.", "Proverbs 31:8-9"),
        ("xr_012", .servantLeader, "What responsibility did you own instead of passing it off?", "Took the blame. Handled a difficult conversation. Followed through.", "Luke 16:10"),
        ("xr_013", .servantLeader, "How did you serve your wife or family sacrificially today?", "Cancelled plans to be present. Listened without defending.", "Ephesians 5:25"),
        ("xr_014", .servantLeader, "How did you leave a place or person better than you found them?", "Cleaned up after others. Encouraged someone who was down. Left a generous tip.", "Hebrews 13:16"),
        ("xr_015", .servantLeader, "Where did you build someone up instead of tearing them down?", "Complimented a coworker publicly. Told my wife what I appreciate.", "Ephesians 4:29"),
        ("xr_016", .servantLeader, "Where did you choose humility over asserting your authority?", "Asked for input. Apologized first. Admitted I did not know.", "Proverbs 11:2"),
        ("xr_017", .servantLeader, "How did you put love into action today?", "Wrote an encouragement note. Helped without being asked. Made a meal for someone.", "1 John 3:18"),
        ("xr_018", .servantLeader, "How did you lead from behind today, empowering someone else?", "Encouraged a teammate to present. Supported a decision publicly.", "John 3:30"),
        ("xr_019", .servantLeader, "How did you model responsibility to those watching your life?", "Kept a commitment. Followed through. Showed up on time.", "Titus 2:7-8"),

        // Truth-Teller (20-38)
        ("xr_020", .truthTeller, "Where did you speak truth in love today?", "Told a friend I was worried about them. Gave honest feedback at work.", "Ephesians 4:15"),
        ("xr_021", .truthTeller, "What hard conversation did you have that you had been avoiding?", "Addressed a conflict. Brought up finances. Talked about a struggle.", "Proverbs 27:6"),
        ("xr_022", .truthTeller, "How did you share your faith with someone today?", "Mentioned what I was reading. Shared how God helped me. Invited someone to church.", "1 Peter 3:15"),
        ("xr_023", .truthTeller, "Where did you choose honesty over image management?", "Admitted I was struggling. Did not exaggerate. Said I do not know.", "Proverbs 12:22"),
        ("xr_024", .truthTeller, "What truth did you speak to yourself that you needed to hear?", "I am not defined by my failures. God is not done with me.", "Romans 8:1"),
        ("xr_025", .truthTeller, "How did you practice vulnerability today?", "Shared a struggle. Admitted a weakness. Asked for help.", "James 5:16"),
        ("xr_026", .truthTeller, "What did you confess today?", "Confessed a sin. Admitted a habit. Told the truth about what I have been hiding.", "1 John 1:9"),
        ("xr_027", .truthTeller, "Where did you refuse to compromise your integrity?", "Did not cut corners. Kept a promise. Told the truth when lying was easier.", "Proverbs 10:9"),
        ("xr_028", .truthTeller, "How did you encourage another man in his faith with a word of truth?", "Texted a verse. Called to check in. Shared what God has been teaching me.", "Hebrews 10:24-25"),
        ("xr_029", .truthTeller, "What boundary did you set that required honest communication?", "Said no to an invitation. Set a limit on screen time. Asked for space.", "Matthew 5:37"),
        ("xr_030", .truthTeller, "Where did you stand for truth when the crowd went the other way?", "Refused to laugh at a degrading joke. Spoke up in a meeting.", "Romans 12:2"),
        ("xr_031", .truthTeller, "What lie did you expose today?", "Called out a rationalization. Challenged gossip. Corrected a false narrative.", "John 8:32"),
        ("xr_032", .truthTeller, "How did you glorify God with your speech today?", "Gave credit to God. Prayed out loud with someone. Spoke words of life.", "Colossians 4:6"),
        ("xr_033", .truthTeller, "How did you live authentically today?", "Acted the same at work as at home. Kept my thoughts clean when alone.", "Psalm 15:2"),
        ("xr_034", .truthTeller, "What sin or pattern did you name honestly instead of minimizing?", "Called my scrolling what it is. Admitted my anger problem.", "Psalm 32:5"),
        ("xr_035", .truthTeller, "Where did you choose to be direct instead of passive-aggressive?", "Said what I meant. Addressed the issue face-to-face.", "Ephesians 4:25"),
        ("xr_036", .truthTeller, "What wisdom did you share with someone younger?", "Mentored a colleague. Shared a life lesson with my kids.", "Proverbs 27:17"),
        ("xr_037", .truthTeller, "How did you use your words to build someone up in truth?", "Affirmed character. Told my kid I am proud of them.", "Proverbs 16:24"),
        ("xr_038", .truthTeller, "How did you correct or challenge someone in a way that honored them?", "Gave constructive feedback gently. Pointed out a blind spot with empathy.", "Galatians 6:1"),

        // Prayer Warrior (39-57)
        ("xr_039", .prayerWarrior, "Who did you intercede for in prayer today?", "Prayed for my wife. Lifted a friend up. Interceded for my kids.", "1 Timothy 2:1"),
        ("xr_040", .prayerWarrior, "How did you bring your struggles to God instead of solving them yourself?", "Prayed about a financial worry. Brought my anger to God.", "Philippians 4:6-7"),
        ("xr_041", .prayerWarrior, "What did you pray about that you have never prayed about before?", "Prayed for an enemy. Prayed about a generational pattern.", "Matthew 7:7"),
        ("xr_042", .prayerWarrior, "Where did you pause to pray before reacting?", "Prayed before responding to an email. Paused before a conversation.", "Psalm 141:3"),
        ("xr_043", .prayerWarrior, "How did you pray for your wife or family today?", "Prayed over sleeping kids. Asked God to bless my wife's day.", "Job 1:5"),
        ("xr_044", .prayerWarrior, "What burden did you carry to God that you have been holding alone?", "Told God about my fear. Prayed about a secret struggle.", "1 Peter 5:7"),
        ("xr_045", .prayerWarrior, "How did you pray for someone who does not know Christ?", "Prayed for a coworker. Asked God to open doors with a neighbor.", "Romans 10:1"),
        ("xr_046", .prayerWarrior, "Where did you worship God in prayer without asking for anything?", "Thanked God for who He is. Worshipped during my drive.", "Psalm 100:4"),
        ("xr_047", .prayerWarrior, "How did you pray Scripture today?", "Prayed Psalm 23 over my day. Claimed a promise from Isaiah.", "Isaiah 55:11"),
        ("xr_048", .prayerWarrior, "What confession did you bring to God in prayer?", "Confessed pride. Admitted lust. Brought anger to the cross.", "1 John 1:9"),
        ("xr_049", .prayerWarrior, "How did you pray for a brother in your circle?", "Texted for prayer requests. Prayed silently for a marriage.", "James 5:16"),
        ("xr_050", .prayerWarrior, "Where did you practice listening to God instead of just talking?", "Sat in silence. Journaled what I felt God saying.", "1 Samuel 3:10"),
        ("xr_051", .prayerWarrior, "How did you pray about your work?", "Asked God for wisdom. Prayed for my boss. Invited God into my to-do list.", "Colossians 3:23"),
        ("xr_052", .prayerWarrior, "What area of spiritual warfare did you engage in prayer?", "Prayed against temptation. Claimed victory over a habitual sin.", "Ephesians 6:18"),
        ("xr_053", .prayerWarrior, "How did you start or end your day with intentional prayer?", "Prayed before my feet hit the floor. Ended with gratitude.", "Psalm 5:3"),
        ("xr_054", .prayerWarrior, "What thanksgiving did you offer God today?", "Thanked Him for family. Expressed gratitude for provision.", "1 Thessalonians 5:18"),
        ("xr_055", .prayerWarrior, "How did you pray for your church or pastor?", "Prayed for Sunday's sermon. Lifted up leadership. Asked for unity.", "Hebrews 13:17"),
        ("xr_056", .prayerWarrior, "Where did you pray when you did not feel like it?", "Prayed through exhaustion. Showed up even when words did not flow.", "Romans 8:26"),
        ("xr_057", .prayerWarrior, "What did you surrender to God in prayer that you had been controlling?", "Gave God the outcome. Released my timeline. Surrendered my plan.", "Proverbs 16:3"),

        // Provider & Protector (58-76)
        ("xr_058", .providerProtector, "How did you provide for or protect someone in your care?", "Worked hard at my job. Made a financial decision for my family.", "1 Timothy 5:8"),
        ("xr_059", .providerProtector, "What did you do to create safety for your family?", "Locked the doors. Had a calm conversation. Prayed protection over my home.", "Psalm 127:1"),
        ("xr_060", .providerProtector, "Where did you step between someone and harm?", "Defended someone being talked about. Protected my kids from harmful content.", "Proverbs 31:8-9"),
        ("xr_061", .providerProtector, "How did you steward your finances faithfully?", "Stuck to the budget. Saved. Gave generously. Made a wise choice.", "Luke 16:10-11"),
        ("xr_062", .providerProtector, "What did you build or fix today that serves your household?", "Fixed something broken. Organized a space. Set up something that helps.", "Proverbs 24:27"),
        ("xr_063", .providerProtector, "How did you protect your family's time or unity?", "Put the phone away. Said no to protect family time. Guarded against busyness.", "Ecclesiastes 3:1"),
        ("xr_064", .providerProtector, "Where did you work diligently for those who depend on you?", "Put in honest effort. Took on an extra task. Pursued excellence.", "Colossians 3:23"),
        ("xr_065", .providerProtector, "How did you protect someone's reputation or dignity?", "Refused to gossip. Spoke well of someone behind their back.", "Proverbs 11:13"),
        ("xr_066", .providerProtector, "What boundary did you set to protect your home?", "Limited screen time. Set content filters. Had a values conversation.", "Joshua 24:15"),
        ("xr_067", .providerProtector, "How did you prepare for the future today?", "Contributed to savings. Made a plan. Invested in development.", "Proverbs 21:5"),
        ("xr_068", .providerProtector, "Where did you show physical presence when someone needed you?", "Showed up to a game. Was home for bedtime. Sat with someone hurting.", "Deuteronomy 31:6"),
        ("xr_069", .providerProtector, "How did you protect your own heart so you could be strong for others?", "Avoided a trigger. Set a media boundary. Took care of my mental health.", "Proverbs 4:23"),
        ("xr_070", .providerProtector, "What generous act did you perform?", "Tipped extra. Bought someone coffee. Gave to someone in need.", "Proverbs 22:9"),
        ("xr_071", .providerProtector, "Where did you sacrifice comfort for someone's wellbeing?", "Woke up early. Stayed up late to help. Gave up what I wanted.", "John 15:13"),
        ("xr_072", .providerProtector, "How did you protect the emotional safety of your home?", "Spoke calmly. Validated feelings. Created space for honest conversation.", "Ephesians 4:26-27"),
        ("xr_073", .providerProtector, "How did you prepare your children for challenges they will face?", "Had a real conversation about faith. Taught a practical skill.", "Deuteronomy 6:6-7"),
        ("xr_074", .providerProtector, "Where did you stand firm against something threatening your family?", "Said no to a compromising situation. Protected a boundary.", "Nehemiah 4:14"),
        ("xr_075", .providerProtector, "How did you honor God through your work today?", "Worked with integrity. Treated colleagues with respect.", "Colossians 3:17"),
        ("xr_076", .providerProtector, "What practical need did you meet for someone?", "Fixed a meal. Ran an errand. Helped someone move. Provided transportation.", "Matthew 25:35-36"),

        // Disciple Maker (77-95)
        ("xr_077", .discipleMaker, "How did you invest in another man's faith today?", "Shared a book. Had a spiritual conversation. Invited someone to a discipline.", "2 Timothy 2:2"),
        ("xr_078", .discipleMaker, "Who did you mentor, encourage, or challenge today?", "Checked in on a younger man. Shared advice. Challenged a brother.", "Titus 2:6-7"),
        ("xr_079", .discipleMaker, "What spiritual truth did you pass on?", "Shared a verse. Explained a concept. Told someone what God has been teaching me.", "Deuteronomy 6:7"),
        ("xr_080", .discipleMaker, "How did you invite someone into your faith journey?", "Invited someone to pray with me. Asked someone to join my reading plan.", "Mark 1:17"),
        ("xr_081", .discipleMaker, "Where did you model faith for someone watching you?", "Lived consistently at home. Showed grace under pressure.", "1 Corinthians 11:1"),
        ("xr_082", .discipleMaker, "How did you create space for spiritual conversation?", "Asked a deep question. Turned small talk into real talk.", "Colossians 4:5-6"),
        ("xr_083", .discipleMaker, "What did you teach your children about God today?", "Prayed with them. Pointed out God's creation. Answered a faith question.", "Proverbs 22:6"),
        ("xr_084", .discipleMaker, "How did you encourage a struggling brother?", "Sent an encouraging text. Called to check in. Reminded him of God's faithfulness.", "1 Thessalonians 5:11"),
        ("xr_085", .discipleMaker, "Where did you point someone to Christ instead of yourself?", "Gave God credit. Directed someone to Scripture. Prayed with them.", "John 3:30"),
        ("xr_086", .discipleMaker, "How did you invest in your own growth today?", "Read Scripture. Listened to a sermon. Read a book on faith.", "1 Timothy 4:15"),
        ("xr_087", .discipleMaker, "Who did you invite to church, a study, or a faith conversation?", "Invited a friend. Shared about my small group. Asked someone to try Anchor & Arrow.", "Acts 2:42"),
        ("xr_088", .discipleMaker, "What question did you ask that made someone think about their faith?", "What are you learning from God? Who is sharpening you? Are you growing?", "Proverbs 20:5"),
        ("xr_089", .discipleMaker, "How did you share your testimony today?", "Told someone how God changed me. Shared a struggle and how faith carried me.", "Revelation 12:11"),
        ("xr_090", .discipleMaker, "Where did you walk alongside someone instead of just telling them?", "Showed up for a friend. Sat with someone in pain. Did the hard thing together.", "Galatians 6:2"),
        ("xr_091", .discipleMaker, "How did you multiply your faith today?", "Invested in a leader. Taught someone to teach. Encouraged a man to disciple others.", "2 Timothy 2:2"),
        ("xr_092", .discipleMaker, "How did you challenge someone to go deeper?", "Recommended a challenging book. Asked a probing question.", "Hebrews 10:24"),
        ("xr_093", .discipleMaker, "What step did you take to raise the next generation?", "Mentored a younger man. Taught my son about character.", "Psalm 78:4"),
        ("xr_094", .discipleMaker, "How did you share a resource that could change someone's life?", "Texted a podcast link. Gave away a book. Shared a verse with application.", "Proverbs 27:17"),
        ("xr_095", .discipleMaker, "What act of discipleship did you do that you will never get credit for?", "Prayed for someone without telling them. Planted a seed quietly.", "1 Corinthians 3:6"),

        // Mixed roles for remaining prompts (96-193)
        ("xr_096", .servantLeader, "What quiet act of service aligned your actions with Christ?", "Held the door. Picked up litter. Helped carry something. Gave a compliment.", "Galatians 6:9"),
        ("xr_097", .truthTeller, "How did you use your words to speak life today?", "Affirmed someone's value. Encouraged a friend. Spoke hope into a hard situation.", "Proverbs 18:21"),
        ("xr_098", .prayerWarrior, "How did you intercede for your community or nation?", "Prayed for local schools. Asked God for justice. Interceded for leaders.", "Jeremiah 29:7"),
        ("xr_099", .providerProtector, "How did you model responsibility to those watching?", "Kept my word. Showed up on time. Did what I said I would do.", "Titus 2:7-8"),
        ("xr_100", .discipleMaker, "Where did you choose to be present for someone's growth?", "Stayed in a long conversation. Followed up. Made time when I was busy.", "Ecclesiastes 4:9-10"),
        ("xr_101", .servantLeader, "How did you practice selflessness in a practical way today?", "Let someone else choose. Gave the last piece. Deferred to another's preference.", "Romans 12:10"),
        ("xr_102", .truthTeller, "What uncomfortable truth did you need to tell yourself today?", "I have been avoiding God. I need to change this habit. I am not okay.", "Psalm 51:6"),
        ("xr_103", .prayerWarrior, "How did you fight a spiritual battle through prayer?", "Prayed against a stronghold. Declared truth over a lie. Interceded for freedom.", "2 Corinthians 10:4"),
        ("xr_104", .providerProtector, "What wise financial decision did you make today?", "Said no to an impulse purchase. Invested in the future. Gave to the church.", "Proverbs 13:11"),
        ("xr_105", .discipleMaker, "How did you live as an example worth following today?", "Stayed consistent. Chose integrity over convenience. Let my actions preach.", "Philippians 3:17"),
        ("xr_106", .servantLeader, "What did you do today that required you to set aside your ego?", "Served in a role beneath my status. Let someone else lead. Apologized.", "Philippians 2:5-7"),
        ("xr_107", .truthTeller, "How did you choose transparency over secrecy today?", "Shared something I was hiding. Brought a struggle into the light.", "Ephesians 5:13"),
        ("xr_108", .prayerWarrior, "How did you invite God into your daily routine through prayer?", "Prayed during my commute. Asked God for direction before a meeting.", "Colossians 4:2"),
        ("xr_109", .providerProtector, "How did you protect your marriage or closest relationship today?", "Put my phone down. Had an honest conversation. Prioritized quality time.", "Genesis 2:24"),
        ("xr_110", .discipleMaker, "What seed of faith did you plant today that may bear fruit later?", "Mentioned God casually. Lived differently. Let someone see my peace in chaos.", "1 Corinthians 3:6-7"),
        ("xr_111", .servantLeader, "How did you serve someone who could never repay you?", "Helped a stranger. Gave to someone in need. Served without expectation.", "Luke 14:13-14"),
        ("xr_112", .truthTeller, "What conviction did you act on today instead of ignoring?", "Stopped a bad habit. Had the conversation. Made the change I kept putting off.", "James 1:22"),
        ("xr_113", .prayerWarrior, "How did you bring a specific person before God's throne today?", "Named them by name. Prayed for their specific struggle. Lifted their family.", "Ephesians 6:18"),
        ("xr_114", .providerProtector, "How did you create stability for someone who needed it?", "Was a calm presence. Provided structure. Made someone feel safe.", "Psalm 46:1"),
        ("xr_115", .discipleMaker, "How did you point someone to Scripture instead of just your opinion?", "Opened the Bible. Shared a reference. Let God's Word speak instead of me.", "2 Timothy 3:16-17"),
        ("xr_116", .servantLeader, "Where did you serve your community today?", "Volunteered. Helped a neighbor. Contributed to something beyond myself.", "Galatians 6:10"),
        ("xr_117", .truthTeller, "How did you model integrity in your workplace today?", "Did not cut corners. Was honest about a mistake. Gave proper credit.", "Colossians 3:23"),
        ("xr_118", .prayerWarrior, "How did you pray for healing or restoration in someone's life?", "Prayed for a sick friend. Asked God to restore a broken relationship.", "James 5:14-15"),
        ("xr_119", .providerProtector, "How did you guard your children's hearts today?", "Monitored content. Had a hard conversation. Modeled healthy behavior.", "Proverbs 22:6"),
        ("xr_120", .discipleMaker, "How did you equip someone to handle a challenge with faith?", "Shared a principle. Walked them through Scripture. Prayed with them about it.", "Ephesians 4:12"),
        ("xr_121", .servantLeader, "What small act of kindness did you extend today?", "Smiled at a stranger. Held a door. Said thank you. Gave a sincere compliment.", "Ephesians 4:32"),
        ("xr_122", .truthTeller, "Where did you choose accountability over secrecy?", "Told my brother about a struggle. Asked someone to hold me accountable.", "Proverbs 27:17"),
        ("xr_123", .prayerWarrior, "How did you use prayer to anchor yourself before a stressful moment?", "Prayed before a meeting. Breathed and prayed before a conversation. Asked God for patience.", "Philippians 4:6"),
        ("xr_124", .providerProtector, "How did you demonstrate reliability today?", "Showed up when I said I would. Finished what I started. Kept my promise.", "Matthew 5:37"),
        ("xr_125", .discipleMaker, "What act of encouragement did you offer a brother in faith today?", "Sent a text. Left a voicemail. Shared a verse that spoke to his situation.", "1 Thessalonians 5:11"),
        ("xr_126", .servantLeader, "How did you make your home a better place to live today?", "Cleaned without being asked. Cooked a meal. Created a peaceful atmosphere.", "Joshua 24:15"),
        ("xr_127", .truthTeller, "How did you confront a wrong with grace today?", "Addressed a mistake gently. Corrected without condemning. Spoke truth with love.", "2 Timothy 2:25"),
        ("xr_128", .prayerWarrior, "How did you pray for your own spiritual growth today?", "Asked God to mature me. Prayed for discipline. Sought the Spirit's guidance.", "Ephesians 3:16-17"),
        ("xr_129", .providerProtector, "How did you ensure your family had what they needed today?", "Went to work faithfully. Provided emotional support. Was present and available.", "1 Timothy 5:8"),
        ("xr_130", .discipleMaker, "How did you encourage someone to read the Bible today?", "Shared a passage. Recommended a reading plan. Read together with my family.", "Joshua 1:8"),
        ("xr_131", .servantLeader, "Where did you choose to be last so someone else could be first?", "Let someone else go first. Deferred to another's need. Put myself last in line.", "Mark 9:35"),
        ("xr_132", .truthTeller, "How did you celebrate truth in someone's life today?", "Pointed out growth. Celebrated a victory. Affirmed faithfulness.", "Philippians 1:6"),
        ("xr_133", .prayerWarrior, "What praise did you offer God today beyond your requests?", "Worshipped His character. Thanked Him for who He is. Praised without asking.", "Psalm 150:6"),
        ("xr_134", .providerProtector, "How did you protect your own physical or mental health today?", "Exercised. Ate well. Got enough sleep. Set a healthy boundary.", "1 Corinthians 6:19-20"),
        ("xr_135", .discipleMaker, "How did you model faithfulness to the next generation today?", "Showed up consistently. Kept a commitment. Let my kids see my faith.", "Psalm 78:4-7"),
        ("xr_136", .servantLeader, "How did you serve someone in your church community today?", "Volunteered for a task. Welcomed a visitor. Cleaned up after an event.", "1 Peter 4:10"),
        ("xr_137", .truthTeller, "How did you choose authenticity over performance today?", "Stopped pretending. Was honest about how I felt. Let someone see the real me.", "2 Corinthians 12:9"),
        ("xr_138", .prayerWarrior, "How did you use prayer to combat worry today?", "Turned each worry into a prayer. Prayed until peace came. Trusted God with the outcome.", "Matthew 6:25-27"),
        ("xr_139", .providerProtector, "How did you protect your family from spiritual harm today?", "Guarded what entered our home. Prayed over my household. Led a conversation about values.", "Ephesians 6:4"),
        ("xr_140", .discipleMaker, "How did you help someone take their next step in faith?", "Invited them to a group. Shared my story. Offered to pray together.", "Acts 8:30-31"),
        ("xr_141", .servantLeader, "How did you honor God through an act of service today?", "Served cheerfully. Gave my best effort. Did it for His glory, not mine.", "Colossians 3:23-24"),
        ("xr_142", .truthTeller, "How did you speak blessing over someone today?", "Told someone God's truth about them. Spoke words of hope. Affirmed their identity in Christ.", "Numbers 6:24-26"),
        ("xr_143", .prayerWarrior, "How did you intercede for someone going through a trial?", "Prayed for strength. Asked God to comfort them. Lifted up their needs.", "Romans 8:26-27"),
        ("xr_144", .providerProtector, "How did you provide wisdom or guidance to someone in need?", "Shared experience. Offered perspective. Pointed them to someone who could help.", "Proverbs 2:6"),
        ("xr_145", .discipleMaker, "How did you sharpen another man's faith today?", "Had a challenging conversation. Asked hard questions. Spoke truth with love.", "Proverbs 27:17"),
        ("xr_146", .servantLeader, "How did you wash feet today in a modern context?", "Did the unglamorous task. Served in the background. Put someone's needs above my comfort.", "John 13:14-15"),
        ("xr_147", .truthTeller, "Where did you choose to tell the whole truth today?", "Did not leave anything out. Was fully honest. Shared the complete picture.", "Zechariah 8:16"),
        ("xr_148", .prayerWarrior, "How did you make prayer a priority over productivity today?", "Prayed first, then worked. Chose prayer over scrolling. Made time for God before tasks.", "Mark 1:35"),
        ("xr_149", .providerProtector, "How did you stand guard over your family's future today?", "Made a long-term plan. Invested in education. Had a vision conversation.", "Habakkuk 2:2-3"),
        ("xr_150", .discipleMaker, "How did you pass on something you learned from your own mentor?", "Shared wisdom I received. Taught a principle that shaped me. Invested in the chain.", "2 Timothy 2:2"),
        ("xr_151", .servantLeader, "How did you respond to an inconvenience with grace today?", "Did not complain. Adapted without frustration. Saw it as an opportunity to serve.", "James 1:2-4"),
        ("xr_152", .truthTeller, "How did you let your life speak truth louder than your words?", "Acted with consistency. Let my behavior match my beliefs. Was the same person everywhere.", "Matthew 5:16"),
        ("xr_153", .prayerWarrior, "How did you use prayer to prepare for tomorrow?", "Prayed about upcoming challenges. Asked God for wisdom for decisions ahead.", "Psalm 90:12"),
        ("xr_154", .providerProtector, "How did you show your family they are your priority today?", "Chose them over work. Made eye contact. Was fully present.", "Ephesians 5:25-28"),
        ("xr_155", .discipleMaker, "How did you live as a man worth imitating today?", "Practiced what I preach. Showed up with integrity. Led by example.", "1 Corinthians 11:1"),
        ("xr_156", .servantLeader, "Where did you sacrifice your preference for the sake of unity?", "Chose peace over being right. Compromised on a non-essential. Let it go.", "Romans 14:19"),
        ("xr_157", .truthTeller, "How did you speak prophetically into someone's potential today?", "Told someone what I see in them. Spoke to who they are becoming. Called out their gifts.", "1 Corinthians 14:3"),
        ("xr_158", .prayerWarrior, "How did you bring the needs of the world into your prayer life?", "Prayed for a global issue. Interceded for persecuted believers. Lifted up the vulnerable.", "1 Timothy 2:1-2"),
        ("xr_159", .providerProtector, "How did you guard the peace in your home today?", "De-escalated a conflict. Chose calm. Protected the emotional atmosphere.", "Romans 12:18"),
        ("xr_160", .discipleMaker, "How did you demonstrate that faith is a daily commitment, not a one-time decision?", "Showed up again. Practiced discipline. Chose God over convenience.", "Luke 9:23"),
        ("xr_161", .servantLeader, "How did you treat someone the way Christ would treat them?", "With dignity. With patience. With genuine care and attention.", "Matthew 25:40"),
        ("xr_162", .truthTeller, "What conviction did the Holy Spirit bring to your attention today?", "Noticed a pattern. Felt a nudge about a habit. Sensed God pointing to a change.", "John 16:8"),
        ("xr_163", .prayerWarrior, "How did you end today in prayer and thanksgiving?", "Reviewed the day with God. Thanked Him for specifics. Released tomorrow to His hands.", "Psalm 4:8"),
        ("xr_164", .providerProtector, "How did you model strength and tenderness together today?", "Was firm but gentle. Led with authority and compassion. Strong hands, soft heart.", "2 Samuel 22:36"),
        ("xr_165", .discipleMaker, "What fruit of your discipleship efforts did you see today?", "Someone applied what I taught. A mentee grew. A friend moved closer to God.", "Colossians 1:10"),
        ("xr_166", .servantLeader, "How did you carry someone's burden today?", "Listened to their pain. Helped with a load. Took on a task they were struggling with.", "Galatians 6:2"),
        ("xr_167", .truthTeller, "How did you refuse to participate in gossip or slander today?", "Changed the subject. Defended the absent. Walked away from a destructive conversation.", "Proverbs 20:19"),
        ("xr_168", .prayerWarrior, "How did you keep a prayer promise you made to someone?", "Actually prayed for what I said I would pray for. Followed up. Kept my word.", "1 Samuel 12:23"),
        ("xr_169", .providerProtector, "How did you teach your family about generosity today?", "Gave together. Shared resources. Modeled open-handed living.", "2 Corinthians 9:6-7"),
        ("xr_170", .discipleMaker, "How did you make yourself available for God to use today?", "Said yes to an opportunity. Was open to interruptions. Stayed flexible for His plans.", "Isaiah 6:8"),
        ("xr_171", .servantLeader, "How did you practice the discipline of showing up today?", "Was present. Was on time. Was reliable. Followed through.", "Proverbs 25:19"),
        ("xr_172", .truthTeller, "How did you apply a truth from Scripture to a real situation today?", "Used a biblical principle at work. Applied a verse to a conflict. Let Scripture guide a decision.", "James 1:22-25"),
        ("xr_173", .prayerWarrior, "How did you pray with boldness and confidence today?", "Approached God's throne boldly. Asked big. Prayed with expectation.", "Hebrews 4:16"),
        ("xr_174", .providerProtector, "How did you invest in your own character today for the sake of those you lead?", "Read. Reflected. Grew. Became a better version of the man my family needs.", "Proverbs 4:7"),
        ("xr_175", .discipleMaker, "How did you love another man enough to challenge him today?", "Said the hard thing. Pushed back on complacency. Loved him enough to be honest.", "Proverbs 27:6"),
        ("xr_176", .servantLeader, "How did you reflect the heart of Christ in your home today?", "Served without complaint. Loved without condition. Led without ego.", "Ephesians 5:1-2"),
        ("xr_177", .truthTeller, "How did you choose courage over comfort in a conversation today?", "Said what needed to be said. Did not hide behind politeness. Spoke with love and boldness.", "Acts 4:29"),
        ("xr_178", .prayerWarrior, "How did you make your prayer life a priority today over all other spiritual disciplines?", "Prayed first. Everything else flowed from prayer. Made it the foundation.", "Mark 1:35"),
        ("xr_179", .providerProtector, "How did you demonstrate faithfulness in a small responsibility today?", "Handled the mundane with excellence. Treated a small task with the same care as a big one.", "Luke 16:10"),
        ("xr_180", .discipleMaker, "How did you help someone see themselves the way God sees them?", "Spoke identity. Reminded them of their worth. Countered lies with God's truth.", "Ephesians 2:10"),
        ("xr_181", .servantLeader, "How did you practice contentment while still pursuing growth?", "Was grateful for today while working toward tomorrow. Content but not complacent.", "Philippians 4:11-12"),
        ("xr_182", .truthTeller, "How did you let God's Word correct you today instead of resisting it?", "Read something convicting and sat with it. Did not rationalize. Let it change me.", "2 Timothy 3:16"),
        ("xr_183", .prayerWarrior, "How did you use silence as a form of prayer today?", "Sat quietly with God. Did not fill the space with words. Just listened.", "Psalm 46:10"),
        ("xr_184", .providerProtector, "How did you provide emotional security for someone today?", "Reassured them. Was steady. Did not let my mood create instability.", "Proverbs 14:26"),
        ("xr_185", .discipleMaker, "How did you demonstrate patience in someone's spiritual journey?", "Did not rush them. Met them where they are. Trusted God with the timeline.", "Romans 15:1"),
        ("xr_186", .servantLeader, "What would Jesus have done in your situation today, and did you do it?", "Chose compassion. Chose service. Chose others. Chose the cross.", "1 John 2:6"),
        ("xr_187", .truthTeller, "How did you stand on biblical truth when cultural pressure pushed the other way?", "Held my ground. Respectfully disagreed. Did not compromise what I know to be true.", "Romans 12:2"),
        ("xr_188", .prayerWarrior, "How did you bring your gratitude before God today?", "Named specific blessings. Thanked Him for the ordinary. Praised Him for His character.", "Psalm 107:1"),
        ("xr_189", .providerProtector, "How did you actively guard against threats to your family's faith?", "Monitored influences. Had a spiritual conversation. Prayed protection.", "1 Peter 5:8"),
        ("xr_190", .discipleMaker, "How did you create a legacy of faith through your actions today?", "Lived in a way my children will remember. Built something that outlasts me.", "Proverbs 13:22"),
        ("xr_191", .servantLeader, "How did you turn a mundane moment into an act of worship through service?", "Served as unto the Lord. Saw the task as sacred. Brought glory to God in the ordinary.", "1 Corinthians 10:31"),
        ("xr_192", .truthTeller, "How did you practice radical honesty with yourself before God today?", "No pretending. No minimizing. Full transparency with the One who already knows.", "Psalm 139:1-4"),
        ("xr_193", .prayerWarrior, "How did you close today by entrusting everything to God?", "Handed Him the results. Released the worry. Trusted His sovereignty over my sleep.", "Psalm 4:8"),
    ]
}
// swiftlint:enable file_length line_length
